import test from 'node:test';import assert from 'node:assert/strict';import worker from '../worker/index.js';
const token='a'.repeat(64);const session={id:'test',title:'Test study',engineVersion:'0.1.0',snapshot:{caseId:'avnrt-01',now:6000,commands:[]},measurements:[]};
function mock(){const rows=new Map();const objects=new Map();return {DB:{prepare:()=>({bind:(...args)=>({first:async()=>rows.get(args[0]),run:async()=>{rows.set(args[0],{object_key:args[5]});}})})},RECORDINGS:{put:async(k,v)=>objects.set(k,v),get:async(k)=>objects.has(k)?{body:objects.get(k)}:null},ASSETS:{fetch:async()=>new Response('app')}};}
const req=(method='GET',body?,auth=token)=>new Request('https://ep.example/api/session',{method,headers:{Authorization:'Bearer '+auth,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});
test('storage is optional and does not block app hosting',async()=>{const health=await worker.fetch(new Request('https://ep.example/api/health'),{});assert.equal((await health.json()).storage,false);assert.equal((await worker.fetch(req(),{})).status,503);});
test('session save/load is scoped to bearer token',async()=>{const env=mock();assert.equal((await worker.fetch(req('PUT',session),env)).status,200);const loaded=await (await worker.fetch(req(),env)).json();assert.deepEqual(loaded.snapshot,session.snapshot);assert.equal((await worker.fetch(req('GET',undefined,'b'.repeat(64)),env)).status,404);assert.equal((await worker.fetch(req('GET',undefined,'bad'),env)).status,401);});
test('invalid commands and cross-origin writes are rejected',async()=>{const env=mock();assert.equal((await worker.fetch(req('PUT',{...session,snapshot:{...session.snapshot,commands:[{t:0,type:'pace',protocol:{}}]}}),env)).status,400);const r=req('PUT',session);r.headers.set('Origin','https://other.example');assert.equal((await worker.fetch(r,env)).status,403);});
test('all new case sessions round-trip without downgrading engine versions',async()=>{for(const caseId of ['avrt-01','at-01','flutter-01','af-01']){const env=mock();const updated={...session,engineVersion:'0.2.0',snapshot:{...session.snapshot,caseId}};assert.equal((await worker.fetch(req('PUT',updated),env)).status,200);const loaded=await(await worker.fetch(req(),env)).json();assert.equal(loaded.engineVersion,'0.2.0');assert.equal(loaded.snapshot.caseId,caseId);assert.equal((await worker.fetch(req('PUT',{...updated,engineVersion:'0.1.0'}),env)).status,400);}});

test('advanced diagnostic sessions retain maneuver, S3 and mapping commands through storage',async()=>{const env=mock();const updated={...session,engineVersion:'0.4.0',snapshot:{caseId:'scar-vt',now:6000,commands:[{t:0,type:'map',site:1},{t:500,type:'collect-map'},{t:1000,type:'maneuver',maneuver:'entrain',cycle:390,beats:8,output:5,coupling:20,site:'apex',capture:'his-rv'},{t:5000,type:'pace',protocol:{site:'HRA',s1:600,beats:1,s2:280,s3:240,output:5,width:1}}]}};assert.equal((await worker.fetch(req('PUT',updated),env)).status,200);const loaded=await(await worker.fetch(req(),env)).json();assert.deepEqual(loaded.snapshot,updated.snapshot);assert.equal(loaded.engineVersion,'0.4.0');assert.equal((await worker.fetch(req('PUT',{...updated,engineVersion:'0.3.0'}),env)).status,400);});
