import type {ManeuverReport} from './diagnosticAnalysis';
import type {CaseDefinition} from './model';
export const ADVANCED_CASES:CaseDefinition[]=[
 {id:'avnrt-atypical',mechanism:'atypical',title:'The long-RP puzzle',subtitle:'Investigate a long-RP rhythm',description:'A regular tachycardia has atrial activity well after the QRS. Compare ventricular entrainment with a precisely timed ventricular extrastimulus.',difficulty:'Intermediate',fastERP:340,slowDelay:255,advanced:true},
 {id:'avrt-septal',mechanism:'septal',title:'A concentric return',subtitle:'Test ventricular participation',description:'A regular narrow-complex tachycardia has a concentric atrial sequence. Determine whether the ventricle and an accessory connection participate.',difficulty:'Intermediate',fastERP:340,slowDelay:255,advanced:true},
 {id:'his-purkinje',mechanism:'conduction',title:'Syncope and a slow connection',subtitle:'Locate conduction block',description:'A patient with syncope undergoes a conduction study. Measure baseline HV and localize block as atrial pacing accelerates.',difficulty:'Foundation',fastERP:340,slowDelay:255,advanced:true},
 {id:'wpw-study',mechanism:'wpw',title:'Two ways forward',subtitle:'Compare forward routes',description:'The baseline QRS is pre-excited. Test antegrade pathway recovery with atrial extrastimuli, then investigate an induced tachycardia.',difficulty:'Intermediate',fastERP:340,slowDelay:255,advanced:true},
 {id:'pjrt-study',mechanism:'pjrt',title:'The slow return route',subtitle:'Measure a slow return',description:'An incessant long-RP tachycardia has a slowly conducting return limb. Test resetting and rate-dependent retrograde conduction.',difficulty:'Advanced',fastERP:340,slowDelay:255,advanced:true},
 {id:'at-sensitive',mechanism:'sensitive',title:'An unexpected drug response',subtitle:'Interpret a drug response',description:'A regular atrial tachycardia conducts to the ventricles. Establish the pacing response before interpreting a drug-induced termination.',difficulty:'Intermediate',fastERP:340,slowDelay:255,advanced:true},
 {id:'la-macroreentry',mechanism:'macro',title:'A circuit around the mitral annulus',subtitle:'Map an atrial circuit',description:'A patient has organized atrial tachycardia after left atrial ablation. Sample the schematic circuit, entrain at different sites, and test a lesion endpoint.',difficulty:'Advanced',fastERP:340,slowDelay:255,advanced:true},
 {id:'rvot-vt',mechanism:'rvot',title:'An outflow-tract rhythm',subtitle:'Locate a ventricular source',description:'Repetitive ventricular activity occurs independently of atrial timing. Compare surface morphology, local activation and pace maps.',difficulty:'Intermediate',fastERP:340,slowDelay:255,advanced:true},
 {id:'fascicular-vt',mechanism:'fascicular',title:'A Purkinje-related circuit',subtitle:'Investigate local potentials',description:'A regular ventricular tachycardia has a relatively narrow broad-complex morphology. Identify a pre-ventricular local potential and interrogate the circuit.',difficulty:'Advanced',fastERP:340,slowDelay:255,advanced:true},
 {id:'scar-vt',mechanism:'scar',title:'A channel through scar',subtitle:'Interrogate a low-voltage channel',description:'A patient with prior infarction has monomorphic VT. Combine substrate observations and entrainment to distinguish a circuit site from a bystander.',difficulty:'Advanced',fastERP:340,slowDelay:255,advanced:true},
];
export type DiagnosticAction={type:'maneuver';maneuver:'vop'|'aop'|'pvc'|'parahis'|'incremental'|'entrain'|'pacemap'|'induce';cycle:number;beats:number;output:number;coupling:number;site:'apex'|'base';capture:'his-rv'|'rv'|'atrial'}|{type:'map';site:number}|{type:'collect-map'}|{type:'lesion';duration:number;contact:number}|{type:'endpoint'};
export function validDiagnostic(value:unknown):value is DiagnosticAction{
 if(!value||typeof value!=='object')return false;const a=value as Record<string,unknown>;
 if(a.type==='map')return Number.isInteger(a.site)&&Number(a.site)>=0&&Number(a.site)<7;
 if(a.type==='collect-map'||a.type==='endpoint')return true;
 if(a.type==='lesion')return Number.isInteger(a.duration)&&Number(a.duration)>=5&&Number(a.duration)<=30&&typeof a.contact==='number'&&Number.isFinite(a.contact)&&a.contact>=0&&a.contact<=1;
 return a.type==='maneuver'&&['vop','aop','pvc','parahis','incremental','entrain','pacemap','induce'].includes(String(a.maneuver))&&Number.isInteger(a.cycle)&&Number(a.cycle)>=220&&Number(a.cycle)<=1000&&Number.isInteger(a.beats)&&Number(a.beats)>=1&&Number(a.beats)<=30&&typeof a.output==='number'&&Number.isFinite(a.output)&&a.output>=0&&a.output<=20&&Number.isInteger(a.coupling)&&Number(a.coupling)>=0&&Number(a.coupling)<=400&&['apex','base'].includes(String(a.site))&&['his-rv','rv','atrial'].includes(String(a.capture));
}
export const DEFAULT_MANEUVER={type:'maneuver' as const,maneuver:'vop' as const,cycle:330,beats:8,output:5,coupling:20,site:'apex' as const,capture:'his-rv' as const};
export interface MapPoint {site:number;name:string;t:number;activation:number|null;voltage:number;paceMatch:number|null;ppi:number|null}
export interface DiagnosticState {site:number;points:MapPoint[];lesions:number[];tachy:boolean;busy:boolean;endpoint:string|null;report?:ManeuverReport|null;reports?:ManeuverReport[]}
export const EMPTY_DIAGNOSTIC:DiagnosticState={site:0,points:[],lesions:[],tachy:false,busy:false,endpoint:null};
export const MAP_SITES=[['Septal annulus','Inferior septum','High lateral RA','Left lateral annulus','Mitral isthmus','RV septum','Remote site'],['Anterior mitral annulus','Lateral mitral annulus','Mitral isthmus','Inferior mitral annulus','Septal mitral annulus','Roof connection','Adjacent bystander'],['Posteroseptal RVOT','Anterior RVOT','RV free wall','Inferior RV','LV septum','LV lateral wall','Remote RV site'],['Posterior fascicle · proximal','Posterior fascicle · mid','Inferior septal Purkinje','Apical septum','Basal septum','LV free wall','Adjacent bystander'],['Scar channel entrance','Mid-channel','Scar channel exit','Inferior border zone','Lateral border zone','Low-voltage return channel','Adjacent bystander']];
export function mapNames(mechanism:string){return MAP_SITES[mechanism==='macro'?1:mechanism==='rvot'?2:mechanism==='fascicular'?3:mechanism==='scar'?4:0];}
