import {useEffect,useRef,useState,type FormEvent,type ReactNode} from 'react';
import {KeyRound,LogOut,Mail,ShieldCheck,UserRound,Users,X,Copy,Check,ChevronRight} from 'lucide-react';
import {api,type Account} from '../accounts';
interface Person {id:string;userId:string|null;name:string;email:string;phone:string|null;role:'user'|'superuser';status:string;owner:boolean;mustChangePassword:boolean}
interface RequestRow {id:string;kind:'access'|'password';name:string;email:string;note:string;created_at:number;notified_at:number|null}
interface SessionRow {id:string;createdAt:number;expiresAt:number;userAgent:string;current:boolean}
function Input({label,type='text',value,onChange,required=true,autoComplete,maxLength=120,readOnly=false,minLength}:{label:string;type?:string;value:string;onChange:(v:string)=>void;required?:boolean;autoComplete?:string;maxLength?:number;readOnly?:boolean;minLength?:number}){return <label className="account-field">{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)} required={required} autoComplete={autoComplete} maxLength={maxLength} minLength={minLength} readOnly={readOnly}/></label>;}
function PasswordFields({onSubmit,busy,requiredChange=false}:{onSubmit:(current:string,next:string)=>Promise<void>;busy:boolean;requiredChange?:boolean}){
 const [current,setCurrent]=useState(''),[next,setNext]=useState(''),[confirm,setConfirm]=useState(''),[error,setError]=useState('');
 const submit=async(e:FormEvent)=>{e.preventDefault();setError('');if(next!==confirm){setError('The new passwords do not match.');return;}if(next===current){setError('Choose a different new password.');return;}try{await onSubmit(current,next);setCurrent('');setNext('');setConfirm('');}catch(cause){setError(cause instanceof Error?cause.message:'Password change failed.');}};
 return <form className="account-form" onSubmit={submit}><h3>{requiredChange?'Choose your private password':'Change password'}</h3><p>{requiredChange?'Your administrator set a temporary password. Replace it before using your account.':'Confirm your current password. Other signed-in sessions will be revoked.'}</p><Input label={requiredChange?'Temporary password':'Current password'} type="password" value={current} onChange={setCurrent} autoComplete="current-password" maxLength={128}/><Input label="New password" type="password" value={next} onChange={setNext} autoComplete="new-password" maxLength={128} minLength={12}/><Input label="Confirm new password" type="password" value={confirm} onChange={setConfirm} autoComplete="new-password" maxLength={128} minLength={12}/><small>12–128 characters</small>{error&&<p className="account-error" role="alert">{error}</p>}<button className="button save" disabled={busy}><KeyRound size={16}/>{busy?'Updating…':'Update password'}</button></form>;
}
export function AccountDialog({account,configured,invitation,onClose,onRefresh}:{account:Account|null;configured:boolean;invitation:string;onClose:()=>void;onRefresh:()=>Promise<void>}){
 const ref=useRef<HTMLDialogElement>(null);const [view,setView]=useState(invitation?'activate':account?'profile':'login');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [email,setEmail]=useState(''),[displayName,setName]=useState(''),[phone,setPhone]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[website,setWebsite]=useState('');
 const [inviteInfo,setInviteInfo]=useState<{name:string;email:string}|null>(null),[sessions,setSessions]=useState<SessionRow[]>([]);
 const forced=Boolean(account?.mustChangePassword);
 useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close();},[]);
 useEffect(()=>{if(invitation)void api<{email:string;name:string}>('/api/invitations/inspect','POST',{token:invitation}).then(data=>{setInviteInfo(data);setEmail(data.email);setName(data.name);}).catch(cause=>setError(cause.message));},[invitation]);
 useEffect(()=>{if(account){setName(account.name);setPhone(account.phone??'');if(view==='login')setView('profile');}},[account]);
 const task=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');setMessage('');try{await fn();}catch(cause){setError(cause instanceof Error?cause.message:'This action failed.');}finally{setBusy(false);}};
 const switchView=(next:string)=>{setView(next);setError('');setMessage('');setPassword('');setConfirm('');};
 const register=async(e:FormEvent)=>{e.preventDefault();if(password!==confirm){setError('The passwords do not match.');return;}await task(async()=>{await api('/api/register','POST',{name:displayName,email,password,website});try{await api('/api/auth/sign-in/email','POST',{email,password,rememberMe:true});setPassword('');setConfirm('');await onRefresh();onClose();}catch{switchView('login');setMessage('Your account is created. Sign in to continue.');}});};
 const login=async(e:FormEvent)=>{e.preventDefault();await task(async()=>{await api('/api/auth/sign-in/email','POST',{email,password,rememberMe:true});setPassword('');await onRefresh();onClose();});};
 const activate=async(e:FormEvent)=>{e.preventDefault();if(password!==confirm){setError('The passwords do not match.');return;}await task(async()=>{await api('/api/invitations/activate','POST',{token:invitation,name:displayName,password});await api('/api/auth/sign-in/email','POST',{email:inviteInfo?.email,password,rememberMe:true});setPassword('');setConfirm('');await onRefresh();onClose();});};
 const request=async(e:FormEvent)=>{e.preventDefault();await task(async()=>{await api('/api/password-reset-requests','POST',{email,website});setMessage('Your request is saved. If this address belongs to an account, the superuser can help you reset its password.');});};
 const signOut=()=>task(async()=>{await api('/api/auth/sign-out','POST',{});await onRefresh();onClose();});
 const loadSessions=()=>task(async()=>{setSessions((await api<{sessions:SessionRow[]}>('/api/account/sessions')).sessions);switchView('sessions');});
 const passwordChange=async(currentPassword:string,newPassword:string)=>{setBusy(true);try{await api('/api/account/password','POST',{currentPassword,newPassword});await onRefresh();setMessage('Password updated. Other sessions have been signed out.');}finally{setBusy(false);}};
 return <dialog className={'modal account-dialog '+(view==='people'?'account-wide':'')} ref={ref} aria-label="EPSimLab account" onCancel={e=>{if(forced)e.preventDefault();else onClose();}}><div className="modal-heading"><h2><ShieldCheck size={20}/> {forced?'Password update required':account?'Your EPSimLab account':view==='activate'?'Activate your account':'Welcome to EPSimLab'}</h2>{!forced&&<button className="icon-button" aria-label="Close account" onClick={onClose}><X size={20}/></button>}</div>
 <div className="account-content">{account&&!forced&&<><div className="account-identity"><span className="account-avatar">{account.name.split(' ').map(s=>s[0]).slice(0,2).join('')}</span><div><strong>{account.name}</strong><small>{account.email}</small></div><span className="tag">{account.previewing?'User preview':account.owner?'Owner · Superuser':account.effectiveRole==='superuser'?'Superuser':'User'}</span></div><nav className="account-tabs" aria-label="Account sections"><button aria-current={view==='profile'?'page':undefined} onClick={()=>switchView('profile')}>Profile</button><button aria-current={view==='sessions'?'page':undefined} onClick={loadSessions}>Sessions</button>{account.effectiveRole==='superuser'&&<button aria-current={view==='people'?'page':undefined} onClick={()=>switchView('people')}>Accounts</button>}<button onClick={signOut} disabled={busy}><LogOut size={14}/>Sign out</button></nav>{account.role==='superuser'&&<div className="preview-account"><p>{account.previewing?'Previewing the regular-user permissions. Your identity and studies remain your own.':'Test the regular-user experience without signing out.'}</p><button className="button subtle" disabled={busy} onClick={()=>void task(async()=>{await api('/api/account/preview','POST',{enabled:!account.previewing});await onRefresh();setView('profile');})}>{account.previewing?'Exit user preview':'Preview as user'}</button></div>}</>}
 {error&&<p className="account-error" role="alert">{error}</p>}{message&&<p className="account-success" role="status">{message}</p>}
 {!configured&&!account&&<p className="account-notice">Account services are unavailable here. You can still explore the simulator. Account services are needed to save progress.</p>}
 {forced&&<><PasswordFields onSubmit={passwordChange} busy={busy} requiredChange/><button className="text-button" onClick={signOut}>Sign out</button></>}
 {!account&&view==='login'&&<><p className="account-intro">Sign in to keep your studies with your account across devices.</p><form className="account-form" onSubmit={login}><Input label="Email address" type="email" value={email} onChange={setEmail} autoComplete="email" maxLength={254}/><Input label="Password" type="password" value={password} onChange={setPassword} autoComplete="current-password" maxLength={128}/><button className="button save" disabled={busy||!configured}><KeyRound size={16}/>{busy?'Signing in…':'Sign in'}</button></form><div className="account-links"><button className="text-button" onClick={()=>switchView('forgot')}>Forgot your password?</button><button className="text-button" onClick={()=>switchView('register')}>Create an account</button><button className="text-button" onClick={onClose}>Continue exploring as a guest</button></div></>}
 {!account&&view==='activate'&&<><p className="account-intro">Your invitation is ready. Choose a private EPSimLab password.</p>{inviteInfo&&<form className="account-form" onSubmit={activate}><Input label="Invited email" value={inviteInfo.email} onChange={()=>{}} readOnly/><Input label="Full name" value={displayName} onChange={setName} autoComplete="name"/><Input label="New password" type="password" value={password} onChange={setPassword} autoComplete="new-password" minLength={12} maxLength={128}/><Input label="Confirm password" type="password" value={confirm} onChange={setConfirm} autoComplete="new-password" minLength={12} maxLength={128}/><small>12–128 characters. This is a separate EPSimLab account.</small><button className="button save" disabled={busy||!configured}>{busy?'Activating…':'Activate account'}<ChevronRight size={16}/></button></form>}<button className="text-button" onClick={()=>switchView('login')}>Already activated? Sign in</button></>}
 {!account&&view==='register'&&<><h3>Create an account</h3><p className="account-intro">An account lets you save studies and open them on another device. You can use the simulator without one.</p><form className="account-form" onSubmit={register}><Input label="Full name" value={displayName} onChange={setName} autoComplete="name"/><Input label="Email address" type="email" value={email} onChange={setEmail} autoComplete="email" maxLength={254}/><Input label="New password" type="password" value={password} onChange={setPassword} autoComplete="new-password" minLength={12} maxLength={128}/><Input label="Confirm password" type="password" value={confirm} onChange={setConfirm} autoComplete="new-password" minLength={12} maxLength={128}/><label className="account-honeypot" aria-hidden="true">Website<input value={website} onChange={e=>setWebsite(e.target.value)} tabIndex={-1} autoComplete="off"/></label><small>12–128 characters</small><button className="button save" disabled={busy||!configured}>{busy?'Creating account…':'Create account'}</button></form><button className="text-button" onClick={()=>switchView('login')}>Already have an account? Sign in</button></>}
 {!account&&view==='forgot'&&<><h3>Request password help</h3><p className="account-intro">The superuser reviews password-help requests and can provide a temporary password.</p>{!message&&<form className="account-form" onSubmit={request}><Input label="Email address" type="email" value={email} onChange={setEmail} autoComplete="email" maxLength={254}/><label className="account-honeypot" aria-hidden="true">Website<input value={website} onChange={e=>setWebsite(e.target.value)} tabIndex={-1} autoComplete="off"/></label><button className="button save" disabled={busy||!configured}><Mail size={16}/>{busy?'Saving…':'Request password help'}</button></form>}<button className="text-button" onClick={()=>switchView('login')}>Back to sign in</button></>}
 {account&&!forced&&view==='profile'&&<><form className="account-form" onSubmit={e=>{e.preventDefault();void task(async()=>{await api('/api/account/profile','PATCH',{name:displayName,phone});await onRefresh();setMessage('Profile updated.');});}}><Input label="Full name" value={displayName} onChange={setName} autoComplete="name"/><Input label="Sign-in email" value={account.email} onChange={()=>{}} readOnly/><Input label="Phone (optional)" type="tel" value={phone} onChange={setPhone} required={false} autoComplete="tel" maxLength={32}/><button className="button subtle" disabled={busy}>Save profile</button></form><PasswordFields onSubmit={passwordChange} busy={busy}/></>}
 {account&&!forced&&view==='sessions'&&<div className="session-management"><h3>Signed-in sessions</h3><p>Revoke access on another browser or device.</p>{sessions.map(s=><div className="account-row" key={s.id}><div><strong>{s.current?'This browser':'Other session'}</strong><small>{new Date(s.createdAt).toLocaleString()}</small><small>{s.userAgent||'Browser details unavailable'}</small></div>{!s.current&&<button className="button subtle" disabled={busy} onClick={()=>void task(async()=>{await api('/api/account/sessions','POST',{id:s.id});setSessions(sessions.filter(x=>x.id!==s.id));})}>Revoke</button>}</div>)}<button className="button subtle" disabled={busy} onClick={()=>void task(async()=>{await api('/api/account/sessions','POST',{allOthers:true});setSessions(sessions.filter(s=>s.current));setMessage('Other sessions revoked.');})}>Sign out other sessions</button></div>}
 {account&&!forced&&view==='people'&&account.effectiveRole==='superuser'&&<PeoplePanel ownId={account.id}/>}
 </div></dialog>;
}
function PeoplePanel({ownId}:{ownId:string}){
 const [people,setPeople]=useState<Person[]>([]),[requests,setRequests]=useState<RequestRow[]>([]),[audit,setAudit]=useState<{id:string;actor_name:string;action:string;created_at:number}[]>([]);
 const [tab,setTab]=useState('people'),[query,setQuery]=useState(''),[offset,setOffset]=useState(0),[more,setMore]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[link,setLink]=useState(''),[copied,setCopied]=useState(false);
 const [selected,setSelected]=useState<Person|null>(null),[name,setName]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[role,setRole]=useState('user'),[temporary,setTemporary]=useState(''),[confirmAction,setConfirmAction]=useState('');
 const load=async(search=query,start=offset)=>{const data=await api<{people:Person[];hasMore:boolean}>('/api/admin/people?q='+encodeURIComponent(search)+'&offset='+start);setPeople(data.people);setMore(data.hasMore);setRequests((await api<{requests:RequestRow[]}>('/api/admin/requests')).requests);};
 useEffect(()=>{void load().catch(cause=>setError(cause.message));},[]);
 const task=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');setMessage('');try{await fn();}catch(cause){setError(cause instanceof Error?cause.message:'This action failed.');}finally{setBusy(false);}};
 const pick=(p:Person|null)=>{setSelected(p);setName(p?.name??'');setEmail(p?.email??'');setPhone(p?.phone??'');setRole(p?.role??'user');setTemporary('');setConfirmAction('');setLink('');setCopied(false);setMessage('');setError('');};
 const invite=async(id:string)=>{const result=await api<{activationUrl:string}>('/api/admin/invitations','POST',{id});setLink(result.activationUrl);setCopied(false);setMessage('Invitation created. Share this private link with the invited person. It works until activation or revocation.');};
 const save=async(e:FormEvent)=>{e.preventDefault();await task(async()=>{if(selected){const result=await api<{person:Person}>('/api/admin/person','PATCH',{id:selected.id,name,email,phone,role});setSelected(result.person);setMessage('Account updated. Role changes revoke existing sessions.');}else{const result=await api<{person:Person;activationUrl:string}>('/api/admin/people','POST',{name,email,phone});setSelected(result.person);setLink(result.activationUrl);setCopied(false);setMessage('Account invited. Share the private activation link below.');}await load();});};
 const changeStatus=async(status:string)=>{if(!selected)return;await task(async()=>{const result=await api<{person:Person}>('/api/admin/person','PATCH',{id:selected.id,status});setSelected(result.person);setConfirmAction('');setLink('');setMessage(status==='removed'?'Account removed from active access. Its study history is retained.':'Account access updated.');await load();});};
 const adminRequest=async(r:RequestRow)=>{setTab('people');if(r.kind==='access'){pick(null);setName(r.name);setEmail(r.email);}else{const found=await api<{people:Person[]}>('/api/admin/people?q='+encodeURIComponent(r.email));const p=found.people.find(p=>p.email===r.email);if(p)pick(p);else setError('No matching account. Verify the requester before taking action.');}};
 return <div className="people-panel"><div className="account-tabs" aria-label="Administration sections"><button aria-current={tab==='people'?'page':undefined} onClick={()=>setTab('people')}><Users size={15}/>People</button><button aria-current={tab==='requests'?'page':undefined} onClick={()=>setTab('requests')}>Requests ({requests.length})</button><button aria-current={tab==='audit'?'page':undefined} onClick={()=>void task(async()=>{setAudit((await api<{events:typeof audit}>('/api/admin/audit')).events);setTab('audit');})}>Activity</button></div>{error&&<p className="account-error" role="alert">{error}</p>}{message&&<p className="account-success" role="status">{message}</p>}
 {tab==='people'&&<div className="people-grid"><div><form className="account-search" onSubmit={e=>{e.preventDefault();setOffset(0);void task(()=>load(query,0));}}><input aria-label="Search accounts" placeholder="Name or email" value={query} onChange={e=>setQuery(e.target.value)}/><button className="button subtle" disabled={busy}>Search</button></form><button className="button save" onClick={()=>pick(null)}><UserRound size={15}/>Invite someone</button><div className="people-list">{people.map(p=><button key={p.id} className={'person-choice '+(selected?.id===p.id?'selected':'')} onClick={()=>pick(p)}><strong>{p.name}</strong><small>{p.email}</small><span>{p.owner?'Owner · ':''}{p.role==='superuser'?'Superuser':'User'} · {p.status}{p.mustChangePassword?' · Password change required':''}</span></button>)}</div><div className="people-pages"><button className="button subtle" disabled={busy||offset===0} onClick={()=>{const start=Math.max(0,offset-100);setOffset(start);void task(()=>load(query,start));}}>Previous</button><button className="button subtle" disabled={busy||!more} onClick={()=>{setOffset(offset+100);void task(()=>load(query,offset+100));}}>Next</button></div></div>
 <div className="person-editor"><h3>{selected?'Edit account':'Invite a new user'}</h3><form className="account-form" onSubmit={save}><Input label="Account name" value={name} onChange={setName}/><Input label="Account email" type="email" value={email} onChange={setEmail} maxLength={254} readOnly={Boolean(selected?.userId)}/><Input label="Account phone (optional)" type="tel" value={phone} onChange={setPhone} required={false} maxLength={32}/>{selected&&<label className="account-field">Account role<select value={role} onChange={e=>setRole(e.target.value)} disabled={selected.owner||selected.id===ownId}><option value="user">User</option><option value="superuser">Superuser</option></select></label>}<button className="button save" disabled={busy||selected?.status==='removed'}>{busy?'Saving…':selected?'Save account':'Create invitation'}</button></form>
 {link&&<div className="invitation-result"><strong>Private activation link</strong><p>Share only with {email}. Opening the link does not consume it.</p><input aria-label="Activation link" readOnly value={link} onFocus={e=>e.target.select()}/><button className="button subtle" onClick={()=>void task(async()=>{await navigator.clipboard.writeText(link);setCopied(true);})}>{copied?<Check size={15}/>:<Copy size={15}/>} {copied?'Copied':'Copy invitation'}</button></div>}
 {selected&&<div className="person-actions">{selected.status==='invited'&&<><button className="button subtle" disabled={busy} onClick={()=>void task(()=>invite(selected.id))}>Create replacement invitation</button><button className="button subtle" disabled={busy} onClick={()=>void task(async()=>{await api('/api/admin/invitations','POST',{id:selected.id,revoke:true});setLink('');setMessage('Existing invitations revoked.');})}>Revoke invitations</button></>}{!selected.owner&&selected.id!==ownId&&<>{['disabled','removed'].includes(selected.status)?<button className="button subtle" disabled={busy} onClick={()=>void changeStatus(selected.userId?'active':'invited')}>Restore access</button>:<button className="button subtle" disabled={busy} onClick={()=>setConfirmAction('disabled')}>Disable access</button>}{selected.status!=='removed'&&<button className="button subtle danger" disabled={busy} onClick={()=>setConfirmAction('removed')}>Remove account</button>}</>}{confirmAction&&<div className="account-confirm"><p>{confirmAction==='removed'?'Remove':'Disable'} access for <strong>{selected.name}</strong>? Sessions and invitations will be revoked. Saved study history is retained.</p><button className="button save" disabled={busy} onClick={()=>void changeStatus(confirmAction)}>Confirm {confirmAction==='removed'?'removal':'disable'}</button><button className="text-button" onClick={()=>setConfirmAction('')}>Cancel</button></div>}
 {selected.userId&&<button className="button subtle" disabled={busy} onClick={()=>void task(async()=>{await api('/api/admin/revoke-sessions','POST',{id:selected.id});setMessage('Other account sessions revoked.');})}>Revoke account sessions</button>}
 {selected.role==='user'&&selected.status!=='disabled'&&selected.status!=='removed'&&<form className="account-form temporary-password" onSubmit={e=>{e.preventDefault();void task(async()=>{await api('/api/admin/password','POST',{id:selected.id,newPassword:temporary});setTemporary('');const results=await api<{people:Person[]}>('/api/admin/people?q='+encodeURIComponent(selected.email));setSelected(results.people.find(p=>p.id===selected.id)??selected);setMessage('Temporary password set. All sessions were revoked; a password change is required at sign-in. Share the password directly with the account owner.');await load();});}}><h3>Set a temporary password</h3><p>Verify the person’s identity before helping them recover access.</p><Input label="Temporary password for this account" type="password" value={temporary} onChange={setTemporary} autoComplete="new-password" minLength={12} maxLength={128}/><button className="button subtle" disabled={busy}>Set temporary password</button></form>}</div>}
 </div></div>}
 {tab==='requests'&&<div className="account-request-list">{requests.length?requests.map(r=><div className="account-request" key={r.id}><span className="tag">{r.kind==='access'?'Access request':'Password help'}</span><h3>{r.name||r.email}</h3><p>{r.email}</p>{r.note&&<p>{r.note}</p>}<small>{new Date(r.created_at).toLocaleString()}</small><div className="coach-actions"><button className="button save" disabled={busy} onClick={()=>void task(()=>adminRequest(r))}>{r.kind==='access'?'Prepare invitation':'Find account'}</button><button className="button subtle" disabled={busy} onClick={()=>void task(async()=>{await api('/api/admin/requests','PATCH',{id:r.id,status:r.kind==='access'?'declined':'resolved'});await load();})}>{r.kind==='access'?'Decline':'Mark resolved'}</button></div></div>):<p>No pending requests.</p>}</div>}
 {tab==='audit'&&<div className="audit-list">{audit.length?audit.map(e=><div className="account-row" key={e.id}><div><strong>{e.action.replaceAll('.',' ')}</strong><small>{e.actor_name||'Account activation'} · {new Date(e.created_at).toLocaleString()}</small></div></div>):<p>No account activity yet.</p>}</div>}
 </div>;
}
