import {SimulationSpeed} from './SimulationSpeed';
import {useState} from 'react';
import {DEFAULT_MANEUVER,mapNames,validDiagnostic,type DiagnosticAction,type DiagnosticState} from '../engine/curriculum';
import type {CaseDefinition,Protocol} from '../engine/model';
import type {Recording,Measurement} from '../store';
import {Traces} from './Traces';
import './diagnostic.css';
const MANEUVERS=[
 ['vop','Ventricular overdrive','Can the ventricle accelerate the atrium and reset the circuit?','Confirm capture, atrial acceleration and a stable S–A before interpreting the return sequence.'],
 ['aop','Atrial overdrive','Does ventricular timing follow the paced atrial cycle?','Compare A–A, V–V and VA before, during and after pacing.'],
 ['pvc','His-timed PVC','Can a ventricular beat change the next atrial activation while His is refractory?','The stimulus waits for the next antegrade H. Check capture and the actual H-to-stimulus interval.'],
 ['parahis','Para-Hisian pacing','Does loss of His capture change stimulus-to-atrial conduction?','Cardiovert to sinus rhythm first. Keep cycle length fixed and compare His+RV with RV-only capture. Direct atrial capture invalidates the comparison.'],
 ['incremental','Incremental atrial pacing','Where does conduction fail as the atrial rate increases?','Cycle length falls by 20 ms per stimulus to a 220 ms floor. Look for A without H versus H without V.'],
 ['entrain','Entrain from mapping site','Is the selected site connected to the reentrant circuit?','Compare local acceleration and postpacing return at different sites. A captured pulse alone does not prove entrainment.'],
 ['pacemap','Pace from mapping site','Does paced activation resemble the clinical ventricular rhythm?','First store or freeze the clinical recording. Compare paced surface morphology and local stimulus-to-V delay.'],
 ['induce','Induction challenge','Does the authored substrate still support the clinical rhythm?','This seeds a circuit in the teaching model; it is separate from programmed stimulation and does not establish a clinical noninducibility endpoint.'],
] as const;
interface Props {speed:number;onSpeed:(speed:number)=>void;definition:CaseDefinition;state:DiagnosticState;recording:Recording;now:number;cycle:number;paused:boolean;guided:boolean;disabled:boolean;onAction:(a:DiagnosticAction)=>void;onPace:(p:Protocol)=>void;onStop:()=>void;onPause:()=>void;onMeasure:(m:Measurement)=>void;onTreatment:()=>void}
export function DiagnosticLab({speed,onSpeed,definition,state,recording,now,cycle,paused,guided,disabled,onAction,onPace,onStop,onPause,onMeasure,onTreatment}:Props){
 const [tab,setTab]=useState<'maneuvers'|'mapping'>(['macro','rvot','fascicular','scar'].includes(definition.mechanism)?'mapping':'maneuvers');const [settings,setSettings]=useState<Extract<DiagnosticAction,{type:'maneuver'}>>(()=>({...DEFAULT_MANEUVER,maneuver:definition.mechanism==='conduction'?'incremental':'vop',cycle:definition.mechanism==='conduction'?600:Math.max(220,Math.min(1000,Math.round(cycle-30))),beats:definition.mechanism==='conduction'?20:12}));const [prediction,setPrediction]=useState('');const [reveal,setReveal]=useState(false);const [calipers,setCalipers]=useState(false);
 const [s2,setS2]=useState(280),[s3,setS3]=useState(240),[useS3,setUseS3]=useState(false),[duration,setDuration]=useState(10),[contact,setContact]=useState(1);
 const names=mapNames(definition.mechanism),selected=MANEUVERS.find(m=>m[0]===settings.maneuver)!;const locked=disabled||state.busy;const set=(key:string,value:unknown)=>setSettings(s=>({...s,[key]:value}));const report=state.report;
 const mappingAvailable=definition.advanced&&definition.mechanism!=='conduction';
 return <div className="diagnostic-lab">
 <div className="diagnostic-monitor"><div className="diagnostic-bar"><strong>{Math.floor(now/1000)} s · {paused?'Paused':'Live'}</strong><SimulationSpeed speed={speed} onSpeed={onSpeed}/><button className="button subtle" onClick={onPause}>{paused?'Resume':'Pause'}</button><button className="button subtle" aria-pressed={calipers} onClick={()=>{if(!calipers&&!paused)onPause();setCalipers(!calipers);}}>Calipers</button><button className="button subtle" onClick={onTreatment}>Drugs / cardioversion</button></div>
 <Traces recording={recording} end={null} sweep={50} gain={1} gains={[]} visibleChannels={tab==='mapping'||['entrain','pacemap'].includes(settings.maneuver)?['II','V1','HRA','HISd','MAP','RV']:['II','HRA','HISd','CSp','CSd','RV']} calipers={calipers&&paused} onMeasure={onMeasure}/></div>
 <div className="diagnostic-body"><div className="diagnostic-tabs"><button aria-pressed={tab==='maneuvers'} onClick={()=>setTab('maneuvers')}>Diagnostic maneuvers</button><button disabled={!mappingAvailable} aria-pressed={tab==='mapping'} onClick={()=>setTab('mapping')}>Mapping & endpoints</button></div>
 {!definition.advanced&&<p className="diagnostic-note">The original cases retain their original conduction model. Ventricular and atrial pacing are available here; select an advanced case for the full maneuver and mapping workspace.</p>}
 {tab==='maneuvers'?<>
 <label className="diagnostic-field">Maneuver<select aria-label="Diagnostic maneuver" value={settings.maneuver} onChange={e=>{setSettings(s=>({...s,maneuver:e.target.value as typeof s.maneuver,cycle:e.target.value==='parahis'?400:e.target.value==='incremental'?600:Math.max(220,Math.min(1000,Math.round(cycle-30))),beats:e.target.value==='incremental'?20:12}));setReveal(false);}}>{MANEUVERS.filter(m=>(definition.advanced||['vop','aop'].includes(m[0]))&&!(definition.mechanism==='conduction'&&['induce','entrain','pacemap'].includes(m[0]))).map(m=><option key={m[0]} value={m[0]}>{m[1]}</option>)}</select></label>
 {guided&&<div className="diagnostic-question"><strong>{selected[2]}</strong><p>{selected[3]}</p><label>Predict the response<textarea aria-label="Predicted maneuver response" value={prediction} onChange={e=>setPrediction(e.target.value)} placeholder="Which activation should change, and why?"/></label></div>}
 <div className="diagnostic-settings"><label className="diagnostic-field">Cycle length (ms)<input aria-label="Maneuver cycle length" type="number" min="220" max="1000" step="10" value={settings.cycle} onChange={e=>set('cycle',Number(e.target.value))}/></label><label className="diagnostic-field">Pulses<input aria-label="Maneuver pulses" type="number" min="1" max="30" value={settings.beats} onChange={e=>set('beats',Number(e.target.value))}/></label><label className="diagnostic-field">Output (mA)<input aria-label="Maneuver output" type="number" min="0" max="20" step=".5" value={settings.output} onChange={e=>set('output',Number(e.target.value))}/></label><button className="button subtle" onClick={()=>set('cycle',Math.max(220,Math.min(1000,Math.round(cycle-30))))}>Use V–V minus 30 ms</button></div>
 {settings.maneuver==='pvc'&&<label className="diagnostic-field">Delay after next antegrade His (ms)<input aria-label="PVC delay after His" type="number" min="0" max="400" step="10" value={settings.coupling} onChange={e=>set('coupling',Number(e.target.value))}/></label>}
 {['vop','pvc','parahis'].includes(settings.maneuver)&&<label className="diagnostic-field">Ventricular pacing location<select aria-label="Diagnostic pacing location" value={settings.site} onChange={e=>set('site',e.target.value)}><option value="apex">RV apex</option><option value="base">RV base</option></select></label>}
 {settings.maneuver==='parahis'&&<label className="diagnostic-field">Capture configuration<select aria-label="Para-Hisian capture" value={settings.capture} onChange={e=>set('capture',e.target.value)}><option value="his-rv">His + RV</option><option value="rv">RV only</option><option value="atrial">Inadvertent direct atrial capture</option></select></label>}
 {['entrain','pacemap'].includes(settings.maneuver)&&<p className="diagnostic-note">Pacing at {names[state.site]}. Change the location in Mapping & endpoints.</p>}
 <div className="diagnostic-actions"><button className="button save" disabled={locked||!validDiagnostic(settings)} onClick={()=>{onAction(settings);setReveal(true);}}>Perform maneuver</button><button className="button subtle" disabled={!state.busy} onClick={onStop}>Stop pacing</button></div>
 <details className="diagnostic-program"><summary>Programmed stimulation · S1 / S2 / S3</summary><p>Use the cycle length, pulse count and output above for the S1 train.</p><div className="diagnostic-settings"><label className="diagnostic-field">S1–S2 (ms)<input aria-label="Diagnostic S2 interval" type="number" min="180" max="1000" value={s2} onChange={e=>setS2(Number(e.target.value))}/></label><label><input type="checkbox" checked={useS3} onChange={e=>setUseS3(e.target.checked)}/> Add S3</label>{useS3&&<label className="diagnostic-field">S2–S3 (ms)<input aria-label="Diagnostic S3 interval" type="number" min="180" max="1000" value={s3} onChange={e=>setS3(Number(e.target.value))}/></label>}</div><div className="diagnostic-actions">{(['HRA','RVA'] as const).map(site=><button key={site} className="button subtle" disabled={locked||!validDiagnostic(settings)||s2<180||s2>1000||!Number.isFinite(s2)||useS3&&(!Number.isFinite(s3)||s3<180||s3>1000)} onClick={()=>onPace({site,s1:settings.cycle,beats:settings.beats,s2,s3:useS3?s3:null,output:settings.output,width:1})}>Pace {site} S1–S2{useS3?'–S3':''}</button>)}</div></details>
 {report&&<section className="diagnostic-report" aria-label="Maneuver findings"><h3>{report.title} · {report.status}</h3><dl>{report.values.map(v=><div key={v.label}><dt>{v.label}</dt><dd>{v.value}</dd></div>)}</dl>{guided&&<button className="text-button" onClick={()=>setReveal(!reveal)}>{reveal?'Hide interpretation':'Explain the response'}</button>}{guided&&reveal&&<p>{report.interpretation}</p>}</section>}
 {Boolean(state.reports?.length)&&<details className="diagnostic-program"><summary>Previous maneuver findings</summary>{state.reports!.map((r,i)=><section key={i} className="diagnostic-report"><h3>{r.title} · {Math.floor(r.start/1000)} s · {r.status}</h3><dl>{r.values.map(v=><div key={v.label}><dt>{v.label}</dt><dd>{v.value}</dd></div>)}</dl></section>)}</details>}
 </>:<>
 <p className="diagnostic-note">Seven discrete network locations. Record local activation before interpreting return intervals. Geometry and voltage are schematic; this is not a clinical electroanatomic mapping system.</p>
 <div className="diagnostic-map" role="group" aria-label="Mapping locations">{names.map((name,i)=><button key={name} aria-pressed={state.site===i} onClick={()=>onAction({type:'map',site:i})}><span>{i+1}</span>{name}{(state.lesions[i]??0)>0&&<small>{Math.round(state.lesions[i]*100)}% lesion</small>}</button>)}</div>
 <div className="diagnostic-actions"><button className="button save" disabled={disabled} onClick={()=>onAction({type:'collect-map'})}>Collect local activation</button><button className="button subtle" onClick={()=>{setSettings(s=>({...s,maneuver:'entrain',beats:20,cycle:Math.max(220,Math.min(1000,Math.round(cycle-30)))}));setTab('maneuvers');}}>Entrain here</button><button className="button subtle" onClick={()=>{set('maneuver','pacemap');setTab('maneuvers');}}>Pace-map here</button></div>
 <div className="diagnostic-table"><table><thead><tr><th>Site</th><th>Local EGM − reference</th><th>Voltage</th></tr></thead><tbody>{state.points.map((p,i)=><tr key={i}><td>{p.name}</td><td>{p.activation===null?'—':p.activation+' ms'}</td><td>{p.voltage.toFixed(2)} mV</td></tr>)}</tbody></table></div>
 <p className="diagnostic-note">Reference is the nearest recorded A for atrial studies or V for ventricular studies. Negative values precede the reference; collected points remain in the study history.</p>
 <h3>Lesion and reassessment</h3><p>A completed teaching lesion interrupts the relevant modeled tissue. Effects accumulate with contact and exposure. This immediate, compressed lesion model does not prescribe clinical RF settings.</p><div className="diagnostic-settings"><label className="diagnostic-field">Exposure (simulated s)<input aria-label="Diagnostic lesion duration" type="number" min="5" max="30" value={duration} onChange={e=>setDuration(Number(e.target.value))}/></label><label className="diagnostic-field">Contact · {Math.round(contact*100)}%<input aria-label="Diagnostic lesion contact" type="range" min="0" max="1" step=".1" value={contact} onChange={e=>setContact(Number(e.target.value))}/></label></div><div className="diagnostic-actions"><button className="button subtle" disabled={locked||!validDiagnostic({type:'lesion',duration,contact})} onClick={()=>onAction({type:'lesion',duration,contact})}>Apply teaching lesion at site {state.site+1}</button><button className="button subtle" disabled={locked} onClick={()=>onAction({type:'endpoint'})}>Assess current endpoint</button><button className="button subtle" disabled={locked} onClick={()=>onAction({...settings,maneuver:'induce'})}>Repeat induction challenge</button></div>{state.endpoint&&<p role="status" className="diagnostic-note">{state.endpoint}</p>}
 </>}
 <details className="diagnostic-program"><summary>Model scope and references</summary><p>Activation propagates through excitable nodes with recovery, rate-dependent delays and competing arrivals. The model does not implement continuous 3D wavefront collision, validated fusion analysis, patient-specific voltage maps or universal diagnostic cutoffs. A single negative pacing maneuver does not exclude a clinical mechanism. Lesion endpoints and induction challenges are authored teaching examples.</p><a href="https://pubmed.ncbi.nlm.nih.gov/8790042/" target="_blank" rel="noreferrer">Para-Hisian pacing study</a><br/><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC6595359/" target="_blank" rel="noreferrer">Ventricular arrhythmia mapping and ablation consensus</a></details>
 </div></div>;
}
