import {useEffect,useRef,useState} from 'react';
import {BookOpen,ChevronLeft,ChevronRight,X} from 'lucide-react';
import {GLOSSARY,SOURCES,TEACHING} from '../teaching';
import type {MechanismId} from '../engine/model';
export type TourAction='anatomy'|'recording'|'measure'|'pacing'|'freeze'|'diagnosis';
const STEPS=[
 {title:'What is an EP study?',body:'The question is not just “how fast is the heart?” We want to know where the abnormal rhythm starts and which electrical connections keep it going. We record, make a controlled change with pacing, and compare the response.',look:'An EP study is an electrical investigation. This simulator starts after catheters have been positioned.',action:'recording',button:'Show the recordings'},
 {title:'Four catheters, four viewpoints',body:'Think of each catheter as a small set of electrical microphones. HRA listens to the right atrium, His to the conduction system, CS along the coronary sinus, and RV to the right ventricle.',look:'Open the 3D view and select the colored catheter names. The model shows where signals are sampled; it is schematic anatomy.',action:'anatomy',button:'Explore the catheters'},
 {title:'Read the rows together',body:'II and V1 are surface ECG views. The other rows record inside the heart. Their horizontal positions share the same clock, so an event further to the right happened later. Large spikes are not always atrial signals.',look:'Use HRA for atrial activity, the His rows for A–H–V, and RV for ventricular activity. Adjust gain by selecting a channel label.',action:'recording',button:'Show the signal rows'},
 {title:'Measure timing, not just rate',body:'A is atrium, H is His bundle, and V is ventricle. AH and HV describe forward conduction. VA asks how soon the atrium follows the ventricle. A–A and V–V describe each chamber’s own clock.',look:'Pause with calipers, then drag between matching deflections. Rename the interval in Measurements. Signal peaks include template and recording-site delays; use the same fiducial point consistently.',action:'measure',button:'Pause and enable calipers'},
 {title:'Ask a question with pacing',body:'A pacing pulse is a deliberate electrical nudge. S1 is a regular train; S2 is an early extra beat. Capture means the pulse activated tissue. How the rhythm reacts helps identify its driver or return route.',look:'The case coach below explains whether this study needs induction, ventricular pacing, or observation first. Loading settings does not deliver a train.',action:'pacing',button:'Show the stimulator'},
 {title:'Keep the evidence',body:'Freeze stores a segment for review while live recording can continue. Compare before, during, and after an intervention. Separate what you saw from what you think caused it.',look:'Use the frozen review and its time slider. Sign in to save commands and measurements to your account, or export a portable session file.',action:'freeze',button:'Freeze a review segment'},
 {title:'Build an explanation',body:'Choose a mechanism and the observations you actually collected. The debrief checks the current recording and explains what the simplified model can and cannot establish.',look:'You can leave the tour at any time. Guided mode keeps case prompts visible; Challenge hides them. The glossary is always available from Guide.',action:'diagnosis',button:'Open the diagnostic worksheet'}
] as const;
export function Tour({step,onStep,onClose,onAction}:{step:number;onStep:(n:number)=>void;onClose:()=>void;onAction:(a:TourAction)=>void}){
 const s=STEPS[step];const heading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{heading.current?.focus({preventScroll:true});},[step]);
 return <section className="tour-card" aria-label="Guided tour"><div className="learning-heading"><span><BookOpen size={16}/> YOUR FIRST EP STUDY · {step+1} OF {STEPS.length}</span><button className="icon-button" aria-label="Close guided tour" onClick={onClose}><X size={18}/></button></div><progress aria-label="Tour progress" value={step+1} max={STEPS.length}/><div className="tour-content"><div><h2 ref={heading} tabIndex={-1}>{s.title}</h2><p>{s.body}</p></div><div className="tour-try"><strong>In this lab</strong><p>{s.look}</p><button className="button subtle" onClick={()=>onAction(s.action)}>{s.button}<ChevronRight size={14}/></button></div></div><div className="tour-navigation"><button className="button subtle" disabled={step===0} onClick={()=>onStep(step-1)}><ChevronLeft size={14}/>Back</button><span>{step+1} / {STEPS.length}</span><button className="button save" onClick={()=>step===STEPS.length-1?onClose():onStep(step+1)}>{step===STEPS.length-1?'Finish tour':'Next'}<ChevronRight size={14}/></button></div></section>;
}
export function CaseCoach({mechanism,onRun,onGlossary,onDiagnose,disabled}:{mechanism:MechanismId;onRun:()=>void;onGlossary:()=>void;onDiagnose:()=>void;disabled:boolean}){
 const lesson=TEACHING[mechanism];
 return <section className="case-coach" aria-label="Case coach"><div className="learning-heading"><span><BookOpen size={15}/> WHAT ARE WE LOOKING FOR?</span><button className="text-button" onClick={onGlossary}>Glossary</button></div><h2>{lesson.question}</h2><ol>{lesson.tasks.map(t=><li key={t}>{t}</li>)}</ol><div className="coach-actions"><button className="button subtle" onClick={onRun} disabled={disabled}>{lesson.protocolLabel}<ChevronRight size={14}/></button><button className="text-button" onClick={onDiagnose}>Interpret findings</button></div></section>;
}
export function LearningGuide({onStart,onModule0}:{onStart:()=>void;onModule0:()=>void}){
 const [search,setSearch]=useState('');const terms=GLOSSARY.filter(([term,definition])=>(term+' '+definition).toLowerCase().includes(search.toLowerCase()));
 return <div className="learning-guide"><button className="button save" onClick={onModule0}><BookOpen size={16}/>Module 0 · EP foundations</button><p style={{marginTop:16}}>Start from the basics, then investigate a case. The tour uses the actual workspace and never resets your study.</p><button className="button save" onClick={onStart}><BookOpen size={16}/>Start guided tour</button><div className="signal-key" aria-label="Normal forward conduction: atrium, His bundle, ventricle"><span><b>A</b>Atrium</span><i>→<small>AH</small></i><span><b>H</b>His bundle</span><i>→<small>HV</small></i><span><b>V</b>Ventricle</span></div><p className="quiet">Normal forward conduction. Abnormal rhythms may reverse the order, add a loop, or give the atrium and ventricle different clocks.</p><h3>EP in plain language</h3><label className="glossary-search">Find a term<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Try “capture”, “CS” or “VA”"/></label><div className="glossary-list">{terms.map(([term,definition])=><details key={term} open={search.length>0||undefined}><summary>{term}</summary><p>{definition}</p></details>)}{terms.length===0&&<p>No matching terms. Try another word.</p>}</div><details className="learning-sources"><summary>Sources and model boundaries</summary><p>Original teaching text informed by the educational sources below. The five scenarios are a foundational selection, not a ranked prevalence list. Model timings and scoring are authored teaching examples and require expert review.</p>{SOURCES.map(([label,url])=><a key={url} href={url} target="_blank" rel="noreferrer">{label} ↗</a>)}<p>These simulations support introductory observation and selected pacing experiments. The treatment lab adds simplified drug effects, cardioversion, and selected RF targets. Validated clinical algorithms, AF ablation, and implantation are not simulated. The case debrief names its specific limits.</p></details></div>;
}
