import {SimulationSpeed} from './SimulationSpeed';
import {useState} from 'react';
import {FlaskConical,Pause,Play,Square,Zap} from 'lucide-react';
import {DRUGS,TARGETS,CTI_TARGETS,type DrugId,type TargetId,type TherapyAction,type TherapyState} from '../engine/therapy';
import type {LabEvent,MechanismId} from '../engine/model';
import type {Recording} from '../store';
import {Anatomy} from './Anatomy';
import {Traces} from './Traces';
import './treatment.css';
interface Props {advanced?:boolean;onDiagnostic?:()=>void;state:TherapyState;now:number;recording:Recording;mechanism:MechanismId;onAction:(action:TherapyAction)=>void;paused:boolean;onPause:()=>void;disabled:boolean;initialTab:'drugs'|'ablation';speed:number;onSpeed:(speed:number)=>void}
export function TreatmentLab({state,now,recording,mechanism,onAction,paused,onPause,disabled,initialTab,speed,onSpeed,advanced=false,onDiagnostic}:Props){
 const [tab,setTab]=useState(initialTab),[target,setTarget]=useState<TargetId>('slow-pathway');
 const [power,setPower]=useState(30),[duration,setDuration]=useState(10),[contact,setContact]=useState(1);
 const selected=TARGETS.find(t=>t.id===target)!,active=state.rf;const selection=active?.target??target;
 const recent=recording.events.filter(e=>['note','shock'].includes(e.kind)).slice(-8).reverse();
 const ctiComplete=CTI_TARGETS.every(t=>(state.lesions[t]??0)>=1),bothDirections=['cti-clockwise','cti-counterclockwise'].every(d=>state.tests.some(t=>t.direction===d&&t.blocked));
 const doseDisabled=disabled||Boolean(active)||state.shockPending;
 return <div className="treatment-lab">
 <div className="treatment-live"><div className="treatment-toolbar"><div className="treatment-tabs"><button aria-pressed={tab==='drugs'} onClick={()=>setTab('drugs')}><FlaskConical size={16}/>Drugs & cardioversion</button><button aria-pressed={tab==='ablation'} onClick={()=>advanced?onDiagnostic?.():setTab('ablation')}><Zap size={16}/>{advanced?'Mapping & lesions':'Ablation'}</button></div><div className="treatment-clock"><span>{Math.floor(now/1000)} s</span><button className="button subtle" onClick={onPause}>{paused?<Play size={14}/>:<Pause size={14}/>} {paused?'Resume':'Pause'}</button><SimulationSpeed speed={speed} onSpeed={onSpeed}/></div></div>
 <div className="treatment-monitor"><Traces recording={recording} end={now} sweep={50} gain={1} gains={[]} calipers={false} onMeasure={()=>{}} compact/><p>Live II / His / RV · use the main recording workspace for all channels and calipers. {paused?'Clock paused: drug washout and RF delivery are paused too.':''}</p></div></div>
 <div className="treatment-content"><div className="treatment-intro"><p>Make a controlled intervention, watch the response, then test what remains. All controls affect the current study and are included in saved-session replay.</p><p className="treatment-limit">Teaching exposures and compressed RF timing—not dosing or energy prescriptions. Blood pressure, sedation, thromboembolic risk, QT prolongation and proarrhythmia are outside this model. Cardioversion and ibutilide here are rhythm demonstrations, not complete treatment protocols.</p></div>
 {disabled&&<p className="treatment-alert">Replaying a saved study. Treatment controls become available when replay finishes.</p>}
 {state.avBlock&&<div className="treatment-alert" role="status"><strong>Complication: AV conduction injury.</strong> His-region ablation has blocked normal conduction. A slow ventricular escape is modeled. This is not a successful treatment endpoint; reset the case to begin a fresh study.</div>}
 {state.drugs.length>0&&<div className="treatment-effects" aria-label="Active drug effects">{state.drugs.map(d=><span key={d.id}>{DRUGS[d.id].name}<strong>{Math.max(0,Math.ceil((d.until-now)/1000))} s remaining</strong></span>)}</div>}
 {tab==='drugs'?<div className="treatment-grid"><section><h3>Drug challenge</h3><p className="treatment-muted">Fixed, time-limited model effects. Redosing is disabled while an exposure is active. Use 5× speed to observe washout.</p>{(Object.keys(DRUGS) as DrugId[]).map(id=><div className="drug-card" key={id}><div><h4>{DRUGS[id].name}</h4><span>{DRUGS[id].duration/1000} simulated seconds</span></div><p>{DRUGS[id].description}</p><p className="treatment-muted">{DRUGS[id].limit}</p><button className="button subtle" disabled={doseDisabled||state.drugs.some(d=>d.id===id)} onClick={()=>onAction({type:'drug',drug:id})}>Give {DRUGS[id].name}</button></div>)}</section><section className="treatment-shock"><h3>Synchronized cardioversion</h3><p>The simulator arms synchronization and delivers one shock at the next modeled R peak. Without a ventricular trigger within three seconds, it cancels delivery.</p><button className="button save" disabled={disabled||Boolean(active)||state.shockPending} onClick={()=>onAction({type:'cardiovert'})}><Zap size={16}/>Arm & cardiovert</button>{state.shockPending&&<><p role="status">Armed · waiting for ventricular synchronization.</p><button className="button subtle" onClick={()=>onAction({type:'cancel-shock'})}>Cancel shock</button></>}<h4>Conversion is not substrate removal</h4><p>The reentry substrate survives a shock. In the automatic AT example, the atrial driver returns after a brief suppression. RF treatment changes the relevant conduction tissue instead.</p><h4>After an intervention</h4><ol><li>Compare atrial and ventricular timing.</li><li>Look for block, conversion, or recurrence.</li><li>Allow temporary drug effects to end before interpreting an ablation endpoint.</li></ol>{state.lastConversion!==null&&<p className="treatment-muted">Last modeled conversion: {Math.floor(state.lastConversion/1000)} s.</p>}</section></div>:<>
 <div className="treatment-grid"><section><h3>1. Position at a candidate site</h3><p className="treatment-muted">Choose a discrete anatomical target or select its marker in 3D. This first version teaches site selection; it does not simulate free catheter navigation or a measured activation map.</p><Anatomy site="His" onSite={()=>{}} events={recording.events.slice(-50)} now={now} ablation={{target:selection,lesions:state.lesions,active:Boolean(active)}} onTarget={id=>{if(!active)setTarget(id);}}/><label className="treatment-field">Ablation target<select aria-label="Ablation target" value={selection} disabled={Boolean(active)||disabled} onChange={e=>setTarget(e.target.value as TargetId)}>{TARGETS.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><p className={selection==='his-risk'?'treatment-alert':'treatment-muted'}>{(TARGETS.find(t=>t.id===selection)??selected).hint}</p>{mechanism==='af'&&<p className="treatment-alert">AF ablation is not implemented. These targets do not isolate pulmonary veins or eliminate the AF driver. Use the drug and cardioversion examples for this case.</p>}</section>
 <section><h3>2. Deliver RF and observe</h3><p className="treatment-muted">Lesion formation uses cumulative power × contact × time in a compressed teaching model. Partial effects persist. It is not a biothermal lesion model.</p><div className="treatment-settings"><label className="treatment-field">Power (W)<input aria-label="RF power" type="number" min="20" max="40" value={active?.power??power} disabled={Boolean(active)} onChange={e=>setPower(Number(e.target.value))}/></label><label className="treatment-field">Duration (s)<input aria-label="RF duration" type="number" min="5" max="30" value={active?(active.end-active.start)/1000:duration} disabled={Boolean(active)} onChange={e=>setDuration(Number(e.target.value))}/></label></div><label className="treatment-field">Contact quality · {Math.round((active?.contact??contact)*100)}%<input aria-label="RF contact quality" type="range" min="0" max="1" step="0.1" value={active?.contact??contact} disabled={Boolean(active)} onChange={e=>setContact(Number(e.target.value))}/></label><div className="treatment-rf"><strong>{active?'RF delivering · '+Math.ceil((active.end-now)/1000)+' s left':'Generator ready'}</strong><progress aria-label="RF application progress" max="1" value={active?(now-active.start)/(active.end-active.start):0}/><div><button className="button save" disabled={doseDisabled||mechanism==='af'||!Number.isFinite(power)||power<20||power>40||!Number.isInteger(duration)||duration<5||duration>30} onClick={()=>onAction({type:'ablate',target,power,duration,contact})}><Zap size={15}/>Start RF</button><button className="button subtle" disabled={!active||disabled} onClick={()=>onAction({type:'stop-ablation'})}><Square size={15}/>Stop RF</button></div></div><h4>Lesion record</h4><div className="treatment-lesions">{TARGETS.filter(t=>(state.lesions[t.id]??0)>0).map(t=><div key={t.id}><span>{t.short}</span><progress aria-label={t.short+' tissue effect'} max="1" value={state.lesions[t.id]??0}/><strong>{Math.round((state.lesions[t.id]??0)*100)}%</strong></div>)}{!Object.values(state.lesions).some(v=>v!>0)&&<p className="treatment-muted">No tissue effect recorded yet. No contact means no lesion.</p>}</div></section></div>
 <section className="treatment-endpoints"><h3>3. Test the result</h3><p>Termination is an observation. A treatment endpoint requires the appropriate test, an observation period, and awareness of confounding drug effects.</p>{state.drugs.length>0&&<p className="treatment-alert">Drug effects remain active. Reassess after washout before attributing block or noninducibility to a lesion.</p>}<div className="treatment-endpoint-actions"><button className="button subtle" disabled={doseDisabled} onClick={()=>onAction({type:'test',test:'induction'})}>Repeat atrial induction</button><button className="button subtle" disabled={doseDisabled} onClick={()=>onAction({type:'test',test:'va'})}>Test VA with RV pacing</button>{mechanism==='flutter'&&<><button className="button subtle" disabled={doseDisabled} onClick={()=>onAction({type:'test',test:'cti-clockwise'})}>Probe CTI: septal → lateral</button><button className="button subtle" disabled={doseDisabled} onClick={()=>onAction({type:'test',test:'cti-counterclockwise'})}>Probe CTI: lateral → septal</button></>}</div>{mechanism==='flutter'&&<><div className="cti-line" aria-label="CTI line segments">{CTI_TARGETS.map((id,i)=><span className={(state.lesions[id]??0)>=1?'blocked':''} key={id}>Segment {i+1}<strong>{(state.lesions[id]??0)>=1?'Blocked':'Conducting gap'}</strong></span>)}</div><p>{bothDirections&&ctiComplete?'Both directional probes demonstrate block in this simplified line. Observe and repeat testing; this is a model endpoint, not clinical validation.':'A complete lesion line must be tested in both directions. A conducting gap prevents the modeled endpoint.'}</p>{state.tests.map((t,i)=><p className="treatment-muted" key={i}>{t.direction==='cti-clockwise'?'Septal → lateral':'Lateral → septal'}: {t.blocked?'block with longer alternate route':'gap conduction'} · {t.delay} ms at {Math.floor(t.t/1000)} s.</p>)}<p className="treatment-muted">CTI probes calculate conduction through the three-segment line or around its alternate route; they do not generate a full differential-pacing electrogram sequence. Clinical bidirectional-block assessment is more detailed.</p></>}{mechanism==='avnrt'&&<p>Repeat induction, then inspect the recording for sustained reentry. Loss of inducibility in a single model protocol is not a universal clinical endpoint.</p>}{mechanism==='avrt'&&<p>During confirmed RV capture, look for the former distal-CS-first atrial return. The concealed accessory connection is the only VA route in this authored AVRT case.</p>}{mechanism==='at'&&<p>Watch the atrial rhythm after treatment. A shock suppresses this focus briefly; a complete focal lesion removes its driver persistently in this study.</p>}</section></>}
 <section className="treatment-log"><h3>Recent procedure events</h3>{recent.map((e:LabEvent)=><p key={e.id}><time>{(e.t/1000).toFixed(1)} s</time>{e.label}</p>)}</section><details className="treatment-sources"><summary>References and model scope</summary><p>Original teaching behavior informed by drug labels and EP literature. No clinical treatment algorithm, dose recommendation, lesion-size prediction, or success probability is provided. Drug time courses and RF thresholds are authored examples. Lesions persist for the study and replay; reset starts fresh. Clinical validation remains pending.</p><a href="https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=364a4c53-0705-7969-e063-6294a90a1717" target="_blank" rel="noreferrer">Adenosine label</a><a href="https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=59ba978b-a393-421c-9a67-77e690249d88" target="_blank" rel="noreferrer">Esmolol label</a><a href="https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0cf8724a-f0d1-4ce2-b7c1-cf5fac345fd0" target="_blank" rel="noreferrer">Ibutilide label</a><a href="https://pubmed.ncbi.nlm.nih.gov/9538310/" target="_blank" rel="noreferrer">Isoproterenol and AVNRT inducibility</a><a href="https://esc365.escardio.org/journal/60443" target="_blank" rel="noreferrer">Contact force and CTI ablation study</a></details></div></div>;
}
