import type {MechanismId,Protocol} from './engine/model';
const vop:Protocol={site:'RVA',s1:330,beats:8,s2:null,output:5,width:1};
const rows=[
 ['atypical','Atypical AVNRT','Is the ventricle necessary for this long-RP rhythm?','Compare entrainment with a captured His-refractory PVC.','The nodal circuit can sustain itself without the ventricle. A long VA alone does not identify the mechanism.',['regularA','pvcUnchanged']],
 ['septal','Concealed septal AVRT','Can an early ventricular beat alter the atrial return?','Deliver a His-timed PVC; compare the next atrial activation with its expected time.','This accessory connection returns to the septal atrium, producing a concentric sequence. Resetting by an appropriately timed ventricular beat supports pathway participation.',['regularA','pvcReset']],
 ['conduction','His–Purkinje disease','Where does forward conduction fail?','Measure HV, then accelerate atrial pacing and look for H without V.','His activation can continue when the downstream His–Purkinje tissue remains refractory. The block lies below the recorded His signal.',['prolongedHV','infraHis']],
 ['wpw','Manifest accessory pathway','Which forward route reaches the ventricle first?','Compare baseline pre-excitation with premature atrial stimulation.','The accessory route can activate ventricular tissue before the normal His–Purkinje route. Its refractory period differs from AV nodal recovery.',['preexcitation','pacedEvidence']],
 ['pjrt','PJRT','Does the long return interval reflect a decremental accessory connection?','Compare pacing cycle lengths and His-timed PVC responses.','A slowly conducting retrograde pathway supports a long-RP AV reentrant circuit. Nodal conduction can mask it during para-Hisian pacing.',['regularA','pvcReset']],
 ['sensitive','Adenosine-sensitive focal AT','Does drug termination identify the circuit?','Document atrial timing during ventricular pacing before giving adenosine.','This atrial driver can stop with adenosine. Termination alone does not establish AVNRT or AVRT; interpret the preceding pacing evidence.',['regularA','independent']],
 ['macro','Perimitral macroreentrant AT','Which mapped locations participate in the atrial circuit?','Collect activation points and compare entrainment at circuit and bystander sites.','The schematic annular circuit has sequential activation and a connected bystander. Interruption of a critical connection stops the loop.',['regularA','mapCollected']],
 ['rvot','RVOT ventricular arrhythmia','Where does ventricular activation begin?','Compare atrial and ventricular timing, local activation and pace maps.','The ventricular focus is independent of the atrial clock. The earliest local ventricular activation is at the authored outflow-tract origin.',['avDissociation','mapCollected']],
 ['fascicular','Fascicular VT','Can a local Purkinje potential identify a circuit site?','Collect local potentials, then entrain from several positions.','A Purkinje-related loop precedes ventricular activation. The local potential and pacing response should be interpreted together.',['avDissociation','mapCollected']],
 ['scar','Scar-related monomorphic VT','Is a low-voltage site part of the circuit or a bystander?','Combine local activation, voltage observations and entrainment.','The authored scar circuit includes a channel and a connected bystander. Low voltage or a pace-map match alone does not identify a critical isthmus.',['avDissociation','mapCollected']],
] as const;
export const ADVANCED_TEACHING=Object.fromEntries(rows.map(([id,name,question,task,explanation,keyEvidence])=>[id,{name,question,tasks:['Observe baseline signals and form a differential.',task,'Predict the response, perform the maneuver, then explain what the recording establishes.'],explanation,limit:'Reduced deterministic teaching network with fixed mapping sites. Local recovery and competing arrivals are modeled; full 3D propagation, clinical cutoffs and patient-specific physiology are not. No single response is a universal diagnostic rule.',protocol:id==='conduction'?{...vop,site:'HRA',s1:400}:['macro','rvot','fascicular','scar'].includes(id)?null:vop,protocolLabel:'Open diagnostic workspace',keyEvidence:[...keyEvidence]}])) as Record<Exclude<MechanismId,'avnrt'|'avrt'|'at'|'flutter'|'af'>,{name:string;question:string;tasks:string[];explanation:string;limit:string;protocol:Protocol|null;protocolLabel:string;keyEvidence:string[]}>;
