import {useCallback,useEffect,useMemo,useRef,useState,type ReactNode} from 'react';
import {Activity,BookOpen,Bookmark,Check,ChevronDown,ChevronRight,CircleHelp,Clock3,Download,FlaskConical,HeartPulse,Layers,Pause,Play,RotateCcw,Ruler,Save,Settings2,ShieldCheck,Square,Target,Upload,UserRound,Waves,X,Zap} from 'lucide-react';
import SimWorker from './engine/sim.worker?worker&inline';
import {CASES,ENGINE_VERSION,isCompatibleSession,validCommand,type Protocol,type LabEvent} from './engine/model';
import {CHANNELS} from './engine/signals';
import {Recording,saveSession,listSessions,downloadJSON,type Measurement,type Session,type Snapshot} from './store';
import {Traces} from './components/Traces';
import {Anatomy} from './components/Anatomy';
import {DIAGNOSES,TEACHING,assess,observations} from './teaching';
import {CaseCoach,LearningGuide,Tour,type TourAction} from './components/Learning';
import {api,useAccount} from './accounts';
import {TreatmentLab} from './components/TreatmentLab';
import {EMPTY_THERAPY,DRUGS,type TherapyAction,type TherapyState} from './engine/therapy';
import {ModuleZero} from './components/ModuleZero';
const fmt=(t:number)=>`${String(Math.floor(t/60000)).padStart(2,'0')}:${String(Math.floor(t/1000)%60).padStart(2,'0')}.${String(Math.floor(t%1000)).padStart(3,'0')}`;
const initial:Protocol={site:'HRA',s1:500,beats:8,s2:280,output:5,width:1};
function Modal({title,children,onClose,wide=false,className=''}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean;className?:string}){
 const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();},[]);
 return <dialog ref={ref} className={(wide?'modal wide-modal':'modal')+' '+className} aria-label={title} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose();}}><div className="modal-heading"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="Close dialog"><X size={20}/></button></div>{children}</dialog>;
}
function Field({label,unit,value,onChange,min,max,step=10,disabled=false}:{label:string;unit?:string;value:number;onChange:(v:number)=>void;min:number;max:number;step?:number;disabled?:boolean}){return <label className="field"><span>{label}</span><div><input aria-label={label} type="number" value={value} min={min} max={max} step={step} disabled={disabled} onChange={e=>onChange(Number(e.target.value))}/>{unit&&<small>{unit}</small>}</div></label>;}
function Mechanism({events,end}:{events:LabEvent[];end:number}){
 const a=events.filter(e=>e.kind==='activation'&&e.t>end-1700&&e.t<=end);const rows:Record<string,number>={A:32,U:78,L:78,H:122,V:165};const x=(t:number)=>75+(t-(end-1700))/1700*600;const byId=new Map(events.map(e=>[e.id,e]));
 return <svg className="ladder" viewBox="0 0 710 195" role="img" aria-label="Activation ladder with atrial, AV nodal, His and ventricular events"><rect width="710" height="195" fill="#0b1119"/>{[['A',32],['AV node',78],['His',122],['V',165]].map(([label,y])=><g key={label}><text x="12" y={Number(y)+4} fill="#9aa8b9" fontSize="12">{label}</text><line x1="75" x2="690" y1={y} y2={y} stroke="#263241"/></g>)}{a.map(e=>{const prev=byId.get(e.cause??-1);return <g key={e.id}>{prev?.node&&prev.t>end-1700&&<line x1={x(prev.t)} y1={rows[prev.node]} x2={x(e.t)} y2={rows[e.node!]} stroke={e.label.includes('slow')?'#ba91e4':'#506b83'} strokeWidth="1.5"/>}<circle cx={x(e.t)} cy={rows[e.node!]} r="3" fill={e.node==='A'?'#6bb6ff':e.node==='V'?'#69d7aa':e.node==='H'?'#f1c267':'#ba91e4'}/></g>;})}</svg>;
}
export default function App(){
 const {account,openAccount,refresh:refreshAccount}=useAccount();const owner=account?.userId??'guest';
 const accountRef=useRef(account);accountRef.current=account;const identityRef=useRef(owner);const pendingSave=useRef<'save'|'export'|null>(null);
 const [deleteStudy,setDeleteStudy]=useState<string|null>(null);
 const [accountStudies,setAccountStudies]=useState<{id:string;title:string;case_id:string;updated_at:number}[]>([]);
 const [therapy,setTherapy]=useState<TherapyState>(EMPTY_THERAPY);const [speed,setSpeed]=useState(1);
 const [moduleReturn,setModuleReturn]=useState(false);
 const [guided,setGuided]=useState(true);const [tourStep,setTourStep]=useState<number|null>(null);const [tourTarget,setTourTarget]=useState('');const [committed,setCommitted]=useState<ReturnType<typeof assess>|null>(null);
 const [mobilePanel,setMobilePanel]=useState<'recording'|'pacing'|'anatomy'>('recording');
 const showMobilePanel=(panel:'recording'|'pacing'|'anatomy')=>{setMobilePanel(panel);requestAnimationFrame(()=>{const nav=document.querySelector<HTMLElement>('.mobile-workspace-nav');if(nav?.offsetParent!==null)nav?.scrollIntoView({block:'start'});});};
 const [liveRecording]=useState(()=>new Recording());
 const recording=useRef(liveRecording);const worker=useRef<Worker|null>(null);const action=useRef<'save'|'export'|'replay'|null>(null);const currentSnapshot=useRef<Snapshot|null>(null);const fileInput=useRef<HTMLInputElement>(null);
 const [caseId,setCaseId]=useState('avnrt-01');const [time,setTime]=useState(0);const [metrics,setMetrics]=useState({cl:800,rate:75,regular:true});const [paused,setPaused]=useState(false);const [pacing,setPacing]=useState(false);const [replaying,setReplaying]=useState(false);
 const [protocol,setProtocol]=useState<Protocol>(initial);const [sweep,setSweep]=useState(100);const [gain,setGain]=useState(1);const [gains,setGains]=useState(CHANNELS.map(()=>1));const [band,setBand]=useState('standard');const [calipers,setCalipers]=useState(false);
 const [review,setReview]=useState<{recording:Recording;end:number;max:number}|null>(null);const [measurements,setMeasurements]=useState<Measurement[]>([]);const [tab,setTab]=useState('log');const [modal,setModal]=useState<string|null>(()=>location.hash==='#module-0'?'module0':null);const [toast,setToast]=useState('');const [sessions,setSessions]=useState<Session[]>([]);const [chosen,setChosen]=useState('');const [evidence,setEvidence]=useState<string[]>([]);const [result,setResult]=useState(false);const [help,setHelp]=useState(true);const [site,setSite]=useState('HRA');const [title,setTitle]=useState('Untitled study');const [lastSaved,setLastSaved]=useState<Session|null>(null);
 const c=CASES.find(x=>x.id===caseId)??CASES[0];const lesson=TEACHING[c.mechanism];const measureRef=useRef(measurements);measureRef.current=measurements;const titleRef=useRef(title);titleRef.current=title;const caseRef=useRef(caseId);caseRef.current=caseId;
 const notify=(message:string)=>setToast(message);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(t);},[toast]);
 useEffect(()=>{
  const w=new SimWorker();worker.current=w;
  w.onmessage=async e=>{const m=e.data;
   if(m.type==='reset'){setTherapy(EMPTY_THERAPY);recording.current.clear();setTime(0);setReview(null);}
   if(m.type==='frame'){recording.current.append(m.start,m.end,m.data,m.events);setTime(m.end);setMetrics(m.metrics);setTherapy(m.therapy??EMPTY_THERAPY);setPacing(m.pacing);setReplaying(m.replay);}
   if(m.type==='error')notify(m.message);
   if(m.type==='replay-complete'){setPaused(true);setReplaying(false);notify('Replay complete. Resume to continue exploring.');}
   if(m.type==='snapshot'){
    const snapshot=m.snapshot as Snapshot;currentSnapshot.current=snapshot;
    const session:Session={id:crypto.randomUUID(),title:titleRef.current==='Untitled study'?(CASES.find(x=>x.id===caseRef.current)?.title??'EP study'):titleRef.current,savedAt:new Date().toISOString(),engineVersion:ENGINE_VERSION,snapshot,measurements:measureRef.current};
    if(action.current==='export'&&accountRef.current){downloadJSON('epsimlab-session.json',session);notify('Session exported with pacing commands and measurements.');}
    if(action.current==='save'&&accountRef.current){
     const activeAccount=accountRef.current,saveOwner=activeAccount.userId;
     let saved=session,accountSaved=false;
     if(activeAccount){try{const data=await api<{study:Session}>('/api/studies','POST',session);saved=data.study;accountSaved=true;}catch{/* Keep a local fallback below. */}}
     try{await saveSession(saved,saveOwner);if(accountRef.current?.userId===saveOwner){setLastSaved(saved);notify(accountSaved?'Study saved to your account and this device.':'Saved on this device. Account sync failed; use Saved studies to retry.');}}catch{if(accountSaved)notify('Study saved to your account.');else notify('Browser storage unavailable. Use Export to keep this study.');}
    }
    if(action.current==='replay'){setBand('standard');setPaused(false);setResult(true);setTab('mechanism');w.postMessage({type:'replay',snapshot});}
    action.current=null;
   }
  };
  w.postMessage({type:'init',caseId:'avnrt-01'});

  return()=>w.terminate();
 },[]);
 const pause=(value:boolean)=>{setPaused(value);worker.current?.postMessage({type:'pause',value});};
 const reset=(id=caseId)=>{setCaseId(id);setSweep(id==='af-01'?25:id==='flutter-01'?50:100);setMobilePanel('recording');setCommitted(null);setTourTarget('');setProtocol(TEACHING[(CASES.find(c=>c.id===id)??CASES[0]).mechanism].protocol??initial);setSite(TEACHING[(CASES.find(c=>c.id===id)??CASES[0]).mechanism].protocol?.site??'HRA');setPaused(false);setPacing(false);setReplaying(false);setResult(false);setChosen('');setEvidence([]);setMeasurements([]);setReview(null);setCalipers(false);setBand('standard');setTab('log');setTitle('Untitled study');setLastSaved(null);worker.current?.postMessage({type:'init',caseId:id});};
 const capture=()=>{const copy=new Recording();copy.data=recording.current.data.map(a=>a.slice());copy.end=recording.current.end;copy.events=[...recording.current.events];setReview({recording:copy,end:copy.end,max:copy.end});notify('Recording frozen below. Live acquisition continues.');};
 const measure=(m:Measurement)=>{setMeasurements(prev=>[m,...prev].slice(0,100));setTab('evidence');};
 const requestSnapshot=(intent:'save'|'export'|'replay')=>{if(intent!=='replay'&&!accountRef.current){pendingSave.current=intent;pause(true);notify('Sign in or create an account to save. Your current study stays open.');openAccount();return;}action.current=intent;worker.current?.postMessage({type:'snapshot'});};

 useEffect(()=>{const previous=identityRef.current;identityRef.current=owner;if(previous===owner)return;setSessions([]);setAccountStudies([]);setDeleteStudy(null);setModuleReturn(false);setModal(current=>previous==='guest'&&current==='module0'?current:null);if(previous!=='guest'){pendingSave.current=null;action.current=null;reset();}else if(account&&pendingSave.current){const intent=pendingSave.current;pendingSave.current=null;requestSnapshot(intent);}},[owner]);
 const openSaved=async()=>{if(!account){openAccount();return;}setModal('saved');try{setSessions(await listSessions(owner));}catch{notify('Device storage is unavailable. You can still import an exported study.');}if(account){try{setAccountStudies((await api<{studies:typeof accountStudies}>('/api/studies')).studies);}catch{notify('Account studies could not be loaded. Local copies remain available.');}}};
 const load=(s:Session)=>{if(!isCompatibleSession(s.engineVersion,s.snapshot?.caseId)){notify('This saved study uses an unsupported engine version.');return;}setChosen('');setEvidence([]);setCommitted(null);setTourTarget('');setCalipers(false);setMobilePanel('recording');const definition=CASES.find(c=>c.id===s.snapshot.caseId)!;setProtocol(TEACHING[definition.mechanism].protocol??initial);setSite(TEACHING[definition.mechanism].protocol?.site??'HRA');setLastSaved(null);setCaseId(s.snapshot.caseId);setSweep(s.snapshot.caseId==='af-01'?25:s.snapshot.caseId==='flutter-01'?50:100);setMeasurements(s.measurements??[]);setTitle(s.title);setBand('standard');setPaused(false);setResult(true);setTab('mechanism');setModal(null);worker.current?.postMessage({type:'replay',snapshot:s.snapshot});};
 const importFile=async(file:File)=>{try{if(file.size>1000000)throw new Error('Session file is too large.');const s=JSON.parse(await file.text()) as Session;
  if(!isCompatibleSession(s.engineVersion,s.snapshot?.caseId)||!Number.isFinite(s.snapshot.now)||s.snapshot.now<0||s.snapshot.now>14400000||!Array.isArray(s.snapshot.commands)||s.snapshot.commands.length>1000)throw new Error('Unsupported or invalid EPSimLab session.');let last=0;
  for(const command of s.snapshot.commands){if(!validCommand(command,s.engineVersion)||command.t<last||command.t>s.snapshot.now)throw new Error('Invalid command history.');last=command.t;}
  s.measurements=Array.isArray(s.measurements)?s.measurements.filter(m=>typeof m.label==='string'&&typeof m.channel==='string'&&Number.isFinite(m.start)&&Number.isFinite(m.end)).slice(0,100):[];s.title=typeof s.title==='string'?s.title.slice(0,120):'Imported study';load(s);notify('Session imported. Replaying the recorded actions.');
 }catch(err){notify(err instanceof Error?err.message:'Unable to import session.');}};
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(['INPUT','SELECT','TEXTAREA','BUTTON','A','SUMMARY'].includes((e.target as HTMLElement)?.tagName)||modal||document.querySelector('dialog[open]'))return;if(e.code==='Space'){e.preventDefault();pause(!paused);}if(e.key.toLowerCase()==='f')capture();};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[paused,modal]);
 const setP=(key:keyof Protocol,value:unknown)=>setProtocol(p=>({...p,[key]:value}));
 const selectSite=(s:string)=>{setSite(s);if(s==='HRA'||s==='RVA')setP('site',s);};
 const treat=(action:TherapyAction)=>{if(replaying)return;if(paused&&!['stop-ablation','cancel-shock'].includes(action.type))pause(false);worker.current?.postMessage({type:'therapy',action});};
 const changeSpeed=(value:number)=>{setSpeed(value);worker.current?.postMessage({type:'speed',value});};
 const startPacing=()=>{showMobilePanel('recording');if(paused)pause(false);worker.current?.postMessage({type:'pace',protocol});};
 const findings=useMemo(()=>observations(recording.current.events),[Math.floor(time/1000),caseId]);
 const correct=committed?.correct??false;
 const openModule=useCallback(()=>{setTourStep(null);setTourTarget('');setModuleReturn(false);setModal('module0');},[]);
 const closeModule=useCallback(()=>{setModal(null);if(location.hash==='#module-0')history.replaceState(null,'',location.pathname+location.search);},[]);
 useEffect(()=>{const openFromLink=()=>{if(location.hash==='#module-0')openModule();};window.addEventListener('hashchange',openFromLink);return()=>window.removeEventListener('hashchange',openFromLink);},[]);
 const startTour=()=>{setModuleReturn(false);setModal(null);setHelp(false);setGuided(true);setTourStep(0);setTourTarget('');};
 const tourAction=useCallback((action:TourAction)=>{
  if(action==='diagnosis'){setModal('diagnosis');return;}
  const panel=action==='anatomy'?'anatomy':action==='pacing'?'pacing':'recording';showMobilePanel(panel);setTourTarget(panel+'-workspace');
  if(action==='measure'){pause(true);setCalipers(true);}
  if(action==='freeze')capture();
  requestAnimationFrame(()=>document.getElementById(panel+'-workspace')?.scrollIntoView({block:'start',behavior:'smooth'}));
 },[]);
 const modulePractice=useCallback((action:TourAction)=>{closeModule();setModuleReturn(true);tourAction(action);},[closeModule,tourAction]);
 const moduleCases=useCallback(()=>{closeModule();setModuleReturn(true);setModal('cases');},[closeModule]);
 const runLesson=()=>{if(lesson.protocol){setProtocol(lesson.protocol);setSite(lesson.protocol.site);setCalipers(false);pause(false);worker.current?.postMessage({type:'pace',protocol:lesson.protocol});showMobilePanel('recording');}else{pause(true);setCalipers(true);showMobilePanel('recording');}};
 useEffect(()=>{if(!tourTarget)return;const target=document.getElementById(tourTarget);target?.classList.add('tour-focus');return()=>target?.classList.remove('tour-focus');},[tourTarget]);
 const logs=recording.current.events.filter(e=>e.kind==='note'||e.kind==='stimulus').slice(-20).reverse();
 const removeAccountStudy=async(id:string)=>{try{await api('/api/studies','DELETE',{id});setAccountStudies(prev=>prev.filter(s=>s.id!==id));setDeleteStudy(null);notify('Account copy deleted. Any local copy is still available.');}catch(cause){notify(cause instanceof Error?cause.message:'Could not delete this study.');}};
 const loadAccountStudy=async(id:string)=>{try{load((await api<{study:Session}>('/api/studies?id='+encodeURIComponent(id))).study);}catch{notify('This account study could not be opened.');}};
 const syncCloud=async(session:Session)=>{try{const data=await api<{study:Session}>('/api/studies','POST',session);await saveSession(data.study,owner);setLastSaved(data.study);await openSaved();notify('Study saved to your account.');}catch{notify('Account sync failed. Your local study remains available.');}};
 return <div className="app-shell">
  <nav className="rail" aria-label="Primary navigation"><a className="brand-mark" href="https://epsimlab.com" aria-label="EPSimLab home"><Activity size={26}/></a><div className="rail-nav"><button className="rail-button active" aria-label="Diagnostic lab" title="Diagnostic lab" onClick={()=>{setModal(null);setMobilePanel('recording');}}><Waves/><span>Lab</span></button><button className="rail-button" aria-label="Case library" title="Case library" onClick={()=>setModal('cases')}><BookOpen/><span>Cases</span></button><button className="rail-button" aria-label="Saved studies" title="Saved studies" onClick={openSaved}><Bookmark/><span>Saved</span></button><div className="rail-divider"/><button className="rail-button" title="Ablation lab" aria-label="Ablation lab" onClick={()=>setModal('ablation')}><Zap/><span>Ablate</span></button><button className="rail-button" title="Device implant roadmap" aria-label="Device implant roadmap" onClick={()=>setModal('devices')}><HeartPulse/><span>Devices</span></button></div><button className="rail-button help-button" aria-label="Help and model limits" onClick={()=>setModal('help')}><CircleHelp/><span>Guide</span></button><button className="avatar account-avatar-button" aria-label="Open account" onClick={openAccount}><UserRound size={16}/></button></nav>
  <div className="app-body"><header className="topbar"><div className="brand-name">EP<span>SimLab</span><span className="version">PREVIEW 0.6</span></div><div className="breadcrumb">Workspace <ChevronRight size={13}/> Diagnostic study</div><div className="top-actions"><button className="button subtle header-account" aria-label={account?'Your account':'Sign in'} onClick={openAccount}><UserRound size={16}/><span>{account?account.name.split(' ')[0]:'Sign in'}</span></button><span className="local-status"><span/> {account?'Account connected':'Guest session'}</span><button className="button subtle" aria-label="Export" onClick={()=>requestSnapshot('export')}><Download size={15}/><span>Export</span></button><button className="button save" onClick={()=>requestSnapshot('save')}><Save size={15}/><span>Save study</span></button></div></header>
  <div className="workspace-heading"><div><div className="eyebrow">THE ELECTROPHYSIOLOGY WORKSPACE</div><h1>Explore the rhythm.</h1><p>Observe. Pace. Understand the mechanism.</p></div><button className="case-switch" onClick={()=>setModal('cases')}><span className="case-number">{c.legacy?'L':String(CASES.findIndex(x=>x.id===caseId)+1).padStart(2,'0')}</span><span><small>CURRENT CASE</small><strong>{c.title}</strong></span><ChevronDown size={16}/></button></div>
  {account?.previewing&&<div className="account-preview-banner"><span>Previewing regular-user access</span><button className="text-button" onClick={()=>void api('/api/account/preview','POST',{enabled:false}).then(refreshAccount).catch(()=>notify('Could not exit preview. Open your account to retry.'))}>Exit preview</button></div>}
  <div className="learning-bar"><div><button className="button subtle" onClick={()=>setModal('treatment')}><FlaskConical size={15}/>Treat rhythm</button><strong>New to EP?</strong><button className="button save" onClick={openModule}><BookOpen size={15}/>Module 0 · Foundations</button><button className="button subtle" onClick={startTour}><BookOpen size={15}/>{tourStep===null?'Take a guided tour':'Restart tour'}</button><button className="text-button" onClick={()=>setModal('help')}>EP glossary</button></div><div className="learning-mode" aria-label="Learning mode"><button aria-pressed={guided} onClick={()=>setGuided(true)}>Guided</button><button aria-pressed={!guided} onClick={()=>{setGuided(false);setTourStep(null);setTourTarget('');}}>Challenge</button></div></div>
  {(therapy.drugs.length>0||therapy.rf||therapy.shockPending||therapy.avBlock)&&<div className={'therapy-status '+(therapy.avBlock?'injury':'')}><span>{therapy.avBlock?'AV conduction injury · slow escape':therapy.rf?'RF delivering · '+therapy.rf.target:therapy.shockPending?'Cardioversion awaiting synchronization':therapy.drugs.map(d=>DRUGS[d.id].name).join(' · ')+' active'}</span><button className="text-button" onClick={()=>setModal(therapy.rf?'ablation':'treatment')}>Open treatment lab</button>{therapy.rf&&<button className="button subtle" disabled={replaying} onClick={()=>treat({type:'stop-ablation'})}>Stop RF</button>}</div>}
  {tourStep!==null&&<Tour step={tourStep} onStep={n=>{setTourStep(n);setTourTarget('');}} onClose={()=>{setTourStep(null);setTourTarget('');}} onAction={tourAction}/>}
  <nav className="mobile-workspace-nav" aria-label="Study workspace">
   <button aria-pressed={mobilePanel==='recording'} aria-controls="recording-workspace" onClick={()=>showMobilePanel('recording')}><Waves size={17}/>Recordings</button>
   <button aria-pressed={mobilePanel==='pacing'} aria-controls="pacing-workspace" onClick={()=>showMobilePanel('pacing')}><Zap size={17}/>Pacing</button>
   <button aria-pressed={mobilePanel==='anatomy'} aria-controls="anatomy-workspace" onClick={()=>showMobilePanel('anatomy')}><Layers size={17}/>Anatomy</button>
  </nav>
  <main className="workspace" data-mobile-panel={mobilePanel}>
   <aside className="context-column" id="anatomy-workspace"><section className="panel case-panel"><div className="panel-heading"><span><FlaskConical size={15}/> Case briefing</span><span className="tag">{c.difficulty}</span></div><div className="case-body"><h2>{c.title}</h2><p>{c.description}</p><div className="case-tags"><span>Diagnostic study</span><span>Fixed catheters</span></div><div className="objective"><Target size={16}/><div><strong>Your objective</strong><p>{guided?lesson.question:'Identify the mechanism and collect supporting evidence.'}</p></div></div></div></section>
   <section className="panel anatomy-panel"><div className="panel-heading"><span><Layers size={15}/> Heart & catheters</span><span className="tiny-label">4 CATHETERS</span></div><Anatomy site={site} onSite={selectSite} events={recording.current.events.slice(-50)} now={time} explain={result}/><div className="catheter-key">{[{s:'HRA',name:'High right atrium',color:'#6bb6ff'},{s:'His',name:'His bundle',color:'#f1c267'},{s:'CS',name:'Coronary sinus',color:'#c291ef'},{s:'RVA',name:'RV apex',color:'#69d7aa'}].map(x=><button key={x.s} className={site===x.s?'selected':''} onClick={()=>selectSite(x.s)}><i style={{background:x.color}}/><span>{x.name}</span><span>{site===x.s?<Check size={12}/>:x.s}</span></button>)}</div><div className="panel-foot">{site==='His'||site==='CS'?'Recording catheter · pacing from HRA or RV in this release':'Selected for stimulation · fixed position'}</div></section>
   <button className="guide-card" onClick={()=>setModal('help')}><BookOpen size={18}/><span><strong>A little guidance?</strong><small>Explore the controls and study workflow</small></span><ChevronRight size={15}/></button></aside>
   <div className="recording-column" id="recording-workspace">{guided&&<CaseCoach mechanism={c.mechanism} onRun={runLesson} onGlossary={()=>setModal('help')} onDiagnose={()=>setModal('diagnosis')} disabled={pacing||replaying}/>}<section className="panel recording-panel"><div className="recording-header"><div><span className={'live-dot '+(paused?'paused':'')}/><strong>{replaying?'SESSION REPLAY':paused?'ACQUISITION PAUSED':'LIVE RECORDING'}</strong><span className="sample-rate">2,000 Hz</span></div><span className="recording-clock"><Clock3 size={13}/>{fmt(time)}</span></div>
   <div className="recording-toolbar"><div className="tool-group"><label>Sweep <select aria-label="Sweep speed" value={sweep} onChange={e=>setSweep(Number(e.target.value))}>{[25,50,100,200].map(n=><option key={n} value={n}>{n} mm/s</option>)}</select></label><label>Gain <select aria-label="Global gain" value={gain} onChange={e=>setGain(Number(e.target.value))}>{[.5,1,2].map(n=><option key={n} value={n}>{n}×</option>)}</select></label></div><div className="tool-group"><button className={'tool-button '+(calipers?'selected':'')} onClick={()=>{if(!calipers)pause(true);setCalipers(!calipers);}} aria-pressed={calipers}><Ruler size={15}/>Calipers</button><button className="tool-button" onClick={capture}><Square size={12}/>Freeze</button></div></div>
   <Traces recording={recording.current} end={null} sweep={sweep} gain={gain} gains={gains} onGain={ch=>setGains(prev=>prev.map((v,i)=>i===ch?(v===.5?1:v===1?2:.5):v))} calipers={calipers&&paused} onMeasure={measure}/>
   <div className="recording-footer"><span><i className="status-dot"/>9 channels <span className="separator">·</span> IC {band==='standard'?'30–500':'100–300'} Hz</span><span>Grid: 500 ms <span className="separator">·</span> Click a label to adjust gain</span></div></section>
   <div className="transport"><button className="transport-play" aria-label={paused?'Resume acquisition':'Pause acquisition'} onClick={()=>pause(!paused)}>{paused?<Play size={17} fill="currentColor"/>:<Pause size={17} fill="currentColor"/>}</button><span>{paused?'Paused':'Acquiring'}<kbd>SPACE</kbd></span><div className="transport-line"><span/></div><button className="tool-button" onClick={capture}><Bookmark size={14}/>Store segment</button><button className="icon-button" aria-label="Reset study" title="Reset study" onClick={()=>setModal('reset')}><RotateCcw size={16}/></button></div>
   {review&&<section className="panel review-panel"><div className="panel-heading"><span><Square size={12}/> Frozen review <span className="tag">{fmt(review.end)}</span></span><div className="tool-group"><button className={'tool-button '+(calipers?'selected':'')} onClick={()=>setCalipers(!calipers)}><Ruler size={13}/>Measure</button><button className="icon-button" aria-label="Close frozen review" onClick={()=>setReview(null)}><X size={15}/></button></div></div><Traces recording={review.recording} end={review.end} sweep={sweep} gain={gain} gains={gains} calipers={calipers} onMeasure={measure} compact annotations={result}/><label className="review-scrubber"><span>Review position</span><input type="range" aria-label="Frozen review position" min={Math.max(1000,review.max-175000)} max={review.max} step="10" value={review.end} onChange={e=>setReview({...review,end:Number(e.target.value)})}/></label></section>}
   <section className="panel evidence-panel"><div className="tabs" role="tablist" aria-label="Study detail"><button role="tab" aria-selected={tab==='log'} onClick={()=>setTab('log')}><Activity size={14}/>Procedure log <span>{logs.length}</span></button><button role="tab" aria-selected={tab==='evidence'} onClick={()=>setTab('evidence')}><Ruler size={14}/>Measurements <span>{measurements.length}</span></button><button role="tab" aria-selected={tab==='mechanism'} onClick={()=>setTab('mechanism')}><Layers size={14}/>Mechanism {result&&<span className="unlocked-dot"/>}</button></div>
   {tab==='log'&&<div className="log-list">{logs.length?logs.map(e=><div className="log-row" key={e.id}><time>{fmt(e.t)}</time><span className={'log-mark '+(e.captured===false?'failed':'')}>{e.kind==='stimulus'?<Zap size={12}/>:<Activity size={12}/>}</span><span>{e.label}</span>{e.kind==='stimulus'&&<small className={e.captured?'captured':'failed'}>{e.captured?'Captured':'No capture'}</small>}</div>):<div className="empty-state"><Activity size={21}/><div><strong>Your study starts here.</strong><p>Deliver a pacing protocol to begin building the procedure log.</p></div></div>}</div>}
   {tab==='evidence'&&<div className="measurement-list">{measurements.length?measurements.map(m=><div className="measurement-row" key={m.id}><Ruler size={14}/><input aria-label="Measurement label" value={m.label} onChange={e=>setMeasurements(prev=>prev.map(x=>x.id===m.id?{...x,label:e.target.value}:x))}/><small>{m.channel}</small><strong>{Math.round(m.end-m.start)} <span>ms</span></strong><button className="icon-button" aria-label="Delete measurement" onClick={()=>setMeasurements(prev=>prev.filter(x=>x.id!==m.id))}><X size={13}/></button></div>):<div className="empty-state"><Ruler size={21}/><div><strong>Make the interval tell its story.</strong><p>Enable calipers, then drag across a recording. Rename measurements AH, HV, VA, or TCL.</p></div></div>}</div>}
   {tab==='mechanism'&&(result?<div className="mechanism-body"><div className="mechanism-title"><span className="tag green">MODEL REVEALED</span><strong>{lesson.name}</strong></div><Mechanism events={recording.current.events} end={time}/><p>{lesson.explanation}</p><p className="quiet">{lesson.limit}</p><button className="button subtle" onClick={()=>requestSnapshot('replay')}><RotateCcw size={14}/>Replay my maneuvers</button></div>:<div className="empty-state"><Layers size={22}/><div><strong>Make your diagnosis first.</strong><p>Commit to a mechanism to reveal the activation ladder and replay your study.</p></div></div>)}
   </section></div>
   <aside className="control-column" id="pacing-workspace"><section className="panel stim-panel"><div className="panel-heading"><span><Zap size={16}/> Stimulator</span><span className={'stim-status '+(pacing?'on':'')}>{pacing?'PACING':'READY'}</span></div><div className="stim-body"><label className="field site-field"><span>STIMULATION SITE</span><select aria-label="Stimulation site" value={protocol.site} onChange={e=>{setP('site',e.target.value);setSite(e.target.value);}}><option value="HRA">HRA 1–2 · Atrium</option><option value="RVA">RV 1–2 · Ventricle</option></select></label><div className="protocol-label"><span>PROGRAMMED STIMULATION</span><button aria-label="Pacing protocol help" className="icon-button" onClick={()=>setModal('protocol')}><CircleHelp size={13}/></button></div><div className="field-grid"><Field label="S1 cycle length" unit="ms" value={protocol.s1} onChange={v=>setP('s1',v)} min={220} max={1500}/><Field label="Drive beats" value={protocol.beats} onChange={v=>setP('beats',v)} min={1} max={30} step={1}/></div><div className="s2-line"><label className="checkbox"><input type="checkbox" checked={protocol.s2!==null} onChange={e=>setP('s2',e.target.checked?280:null)}/><span>Add extrastimulus</span><span className="s-badge">S2</span></label></div>{protocol.s2!==null&&<Field label="S1–S2 coupling interval" value={protocol.s2} unit="ms" onChange={v=>setP('s2',v)} min={180} max={1000}/>}
   <div className="pulse-preview" aria-label="Pacing train schematic">{Array.from({length:Math.min(protocol.beats,12)},(_,i)=><i key={i}/>)}{protocol.s2!==null&&<i className="extra"/>}<span>S1{protocol.s2!==null?' → S2':''}</span></div><div className="field-grid output-fields"><Field label="Output" unit="mA" value={protocol.output} onChange={v=>setP('output',v)} min={0} max={20} step={.5}/><Field label="Pulse width" unit="ms" value={protocol.width} onChange={v=>setP('width',v)} min={.1} max={2} step={.1}/></div><button className={'pace-button '+(pacing?'delivering':'')} onClick={pacing?()=>worker.current?.postMessage({type:'stop'}):startPacing} disabled={replaying}>{pacing?<Square size={15} fill="currentColor"/>:<Zap size={16}/>} {pacing?'Stop pacing':'Deliver pacing train'}<span>{pacing?'':'↵'}</span></button><div className="presets"><span>QUICK PROTOCOLS</span><button onClick={()=>{setProtocol(initial);setSite('HRA');notify('Induction protocol loaded. Deliver the train to test inducibility.');}}>Atrial induction <ChevronRight size={12}/></button><button onClick={()=>{setProtocol({site:'RVA',s1:Math.max(220,metrics.cl-30),beats:12,s2:null,output:5,width:1});setSite('RVA');notify('Ventricular overdrive protocol loaded. Confirm sustained tachycardia and capture.');}}>Ventricular overdrive <ChevronRight size={12}/></button></div></div></section>
   <section className="panel signal-panel"><div className="panel-heading"><span><Settings2 size={14}/> Signal settings</span></div><label className="filter-row"><span>Intracardiac filter</span><select aria-label="Intracardiac filter" value={band} onChange={e=>{setBand(e.target.value);worker.current?.postMessage({type:'band',band:e.target.value});notify('Live filter changed. Allow a brief settling period. Frozen recordings keep their original filter.');}}><option value="standard">30–500 Hz</option><option value="narrow">100–300 Hz</option></select></label><div className="filter-row"><span>Surface ECG</span><strong>0.5–150 Hz</strong></div></section>
   <div className="rhythm-card"><div><span>VENTRICULAR RATE</span><strong>{metrics.rate}<small>bpm</small></strong></div><div><span>MEAN V–V</span><strong>{metrics.cl}<small>ms</small></strong></div><p><span className="status-dot"/>{metrics.rate===0?'No recent ventricular activation':metrics.regular?'Regular ventricular intervals':'Variable ventricular intervals'} · last 4 cycles</p></div>
   <button className="diagnose-button" onClick={()=>setModal('diagnosis')}><Target size={17}/>{result?'Review my diagnosis':'Commit diagnosis'}<ChevronRight size={15}/></button><p className="diagnose-hint">A mechanism is only as strong as its evidence.</p></aside>
  </main><footer className="app-footer"><span><ShieldCheck size={12}/> Synthetic educational model · expert validation pending</span><span>EPSimLab <span className="separator">/</span> Diagnostic EP simulator</span></footer>
  </div>
  <div className="mobile-study-controls" aria-label="Quick study controls">
   <button className="mobile-pause" aria-label={paused?'Resume recording':'Pause recording'} onClick={()=>pause(!paused)}>{paused?<Play size={18}/>:<Pause size={18}/>}<span>{paused?'Resume':'Pause'}</span></button>
   <button className={'mobile-pace '+(pacing?'delivering':'')} disabled={replaying} onClick={pacing?()=>worker.current?.postMessage({type:'stop'}):startPacing}>{pacing?<Square size={17}/>:<Zap size={17}/>}<span>{pacing?'Stop pacing':replaying?'Replaying study':'Deliver pacing'}<small>{protocol.site} · {protocol.beats} × {protocol.s1}{protocol.s2!==null?' + '+protocol.s2:''} ms</small></span></button>
   <button aria-label="Freeze recording" onClick={()=>{capture();showMobilePanel('recording');}}><Square size={16}/><span>Freeze</span></button>
  </div>
  {help&&!guided&&<div className="onboarding-tip"><span className="tip-icon"><Zap size={16}/></span><p><strong>Follow the chamber timing.</strong> Compare atrial and ventricular activity, then use pacing to test your hypothesis. Open Guide for help.</p><button className="icon-button" onClick={()=>setHelp(false)} aria-label="Dismiss tip"><X size={15}/></button></div>}
  {moduleReturn&&<button className="tour-return button save" onClick={openModule}><BookOpen size={15}/>Back to Module 0</button>}
  {tourStep!==null&&tourTarget&&<button className="tour-return button save" onClick={()=>document.querySelector('.tour-card')?.scrollIntoView({block:'start',behavior:'smooth'})}><BookOpen size={15}/>Back to tour · {tourStep+1}/7</button>}
  {toast&&<div className="toast" role="status"><Check size={15}/>{toast}</div>}
  <input ref={fileInput} type="file" accept=".json,application/json" hidden onChange={e=>{if(e.target.files?.[0])void importFile(e.target.files[0]);e.target.value='';}}/>
  {modal==='cases'&&<Modal title="Choose your next study" onClose={()=>setModal(null)}><p className="modal-intro">Five common teaching presentations, each with a distinct rhythm and learning objectives. Cases 2–5 open in the clinical rhythm; case 1 starts in sinus rhythm for induction.</p>{CASES.filter(x=>!x.legacy).map((x,i)=><button key={x.id} className="case-choice" onClick={()=>{reset(x.id);setModal(null);}}><span className="case-number">0{i+1}</span><span><strong>{x.title}</strong><small>{guided?TEACHING[x.mechanism].name:x.subtitle} · {x.difficulty}</small></span><ChevronRight size={18}/></button>)}<p className="quiet">Opening a case starts a new study. Save your current study first if you want to return to it.</p></Modal>}
  {modal==='saved'&&<Modal title="Your saved studies" onClose={()=>setModal(null)}><div className="modal-actions"><button className="button subtle" onClick={()=>fileInput.current?.click()}><Upload size={15}/>Import session</button>{!account&&<button className="button save" onClick={()=>{setModal(null);openAccount();}}>Sign in for account saves</button>}</div>{account&&<><h3 className="saved-section-label">In your account</h3>{accountStudies.length?accountStudies.map(s=><div key={s.id}><div className="saved-account-row"><button className="case-choice" onClick={()=>void loadAccountStudy(s.id)}><Bookmark size={20}/><span><strong>{s.title}</strong><small>{new Date(s.updated_at).toLocaleString()}</small></span><Play size={15}/></button><button className="icon-button" aria-label={"Delete account copy of "+s.title} title="Delete account copy" onClick={()=>setDeleteStudy(s.id)}><X size={17}/></button></div>{deleteStudy===s.id&&<div className="account-confirm"><p>Delete <strong>{s.title}</strong> from your account? Local copies will remain.</p><button className="button subtle danger" onClick={()=>void removeAccountStudy(s.id)}>Delete account copy</button><button className="text-button" onClick={()=>setDeleteStudy(null)}>Cancel</button></div>}</div>):<p className="modal-intro">No account studies loaded yet. Save a study while signed in.</p>}</>}<h3 className="saved-section-label">On this device{account?' · your account':''}</h3>{sessions.length?sessions.map(s=><div className="saved-account-row" key={s.id}><button className="case-choice" onClick={()=>load(s)}><Bookmark size={20}/><span><strong>{s.title}</strong><small>{new Date(s.savedAt).toLocaleString()} · {Math.round(s.snapshot.now/1000)} s</small></span><Play size={15}/></button>{account&&!accountStudies.some(c=>c.id===s.id)&&<button className="icon-button" aria-label={'Save '+s.title+' to account'} title="Save to account" onClick={()=>void syncCloud(s)}><Upload size={17}/></button>}</div>):<div className="modal-empty"><Bookmark size={28}/><h3>A place for your discoveries.</h3><p>Save a study to keep its pacing history and measurements.</p></div>}<p className="modal-intro">Your saved studies are private to your account. Local copies remain available on this device while you are signed in.</p></Modal>}
  {modal==='reset'&&<Modal title="Start this study again?" onClose={()=>setModal(null)}><p className="modal-intro">The current recording and measurements will be cleared. Saved studies remain available.</p><div className="modal-actions"><button className="button subtle" onClick={()=>setModal(null)}>Keep studying</button><button className="button save" onClick={()=>{reset();setModal(null);}}>Reset study</button></div></Modal>}
  {modal==='diagnosis'&&<Modal title={result?'Study debrief':'Make the mechanism explicit'} onClose={()=>setModal(null)} wide><p className="modal-intro">Choose your diagnosis and the findings you actually observed. Checks use the retained live recording (up to three minutes); submit soon after your maneuvers.</p><div className="diagnosis-grid">{DIAGNOSES.map(d=><button key={d.id} className={'diagnosis-option '+(chosen===d.id?'selected':'')} onClick={()=>{setChosen(d.id);setResult(false);}}><span className="radio-dot"/><span><strong>{d.label}</strong><small>{d.sub}</small></span></button>)}</div><div className="evidence-choices"><h3>Supporting observations</h3>{findings.map(f=><label key={f.id} className="checkbox"><input type="checkbox" checked={evidence.includes(f.id)} onChange={e=>{setEvidence(v=>e.target.checked?[...v,f.id]:v.filter(x=>x!==f.id));setResult(false);}}/><span>{f.label}</span></label>)}</div>{result&&<div className={'result-box '+(correct?'correct':'')} role="status"><strong>{correct?'Your diagnosis is supported in this teaching model.':chosen===c.mechanism?'Right mechanism. Strengthen the evidence.':'Study debrief: '+lesson.name}</strong><p>{lesson.explanation}</p>{committed&&<><p>{committed.supported.length} selected observation(s) supported. Key observations for this case: {lesson.keyEvidence.map(id=>findings.find(f=>f.id===id)?.label).join('; ')}.</p><ul className="feedback-observations">{committed.findings.filter(f=>evidence.includes(f.id)).map(f=><li key={f.id}><strong>{f.valid?'Observed':'Not established'}: {f.label}.</strong> {f.why}</li>)}</ul></>}<p className="quiet">{lesson.limit}</p></div>}<div className="modal-actions">{result?<button className="button save" onClick={()=>{setModal(null);setTab('mechanism');}}>Explore the mechanism <ChevronRight size={16}/></button>:<button className="button save" disabled={!chosen||!evidence.length} onClick={()=>{setCommitted(assess(c.mechanism,chosen,evidence,recording.current.events));setResult(true);}}>Commit diagnosis <Target size={15}/></button>}</div></Modal>}
  {modal==='devices'&&<Modal title="Device implantation · next chapter" onClose={()=>setModal(null)}><div className="roadmap-symbol"><HeartPulse size={30}/></div><p className="modal-intro">The planned first implant is a dual-chamber pacemaker: position and fix leads, test sensing and capture, and assess final system function.</p><p className="quiet">Device implantation is planned. Diagnostic studies and the treatment lab are available now.</p></Modal>}
  <ModuleZero open={modal==='module0'} onClose={closeModule} onPractice={modulePractice} onCases={moduleCases}/>
  {(modal==='treatment'||modal==='ablation')&&<Modal className="treatment-dialog" title="Treatment lab · observe, intervene, reassess" onClose={()=>setModal(null)} wide><TreatmentLab state={therapy} now={time} recording={recording.current} mechanism={c.mechanism} onAction={treat} paused={paused} onPause={()=>pause(!paused)} disabled={replaying} initialTab={modal==='ablation'?'ablation':'drugs'} speed={speed} onSpeed={changeSpeed}/></Modal>}
  {modal==='help'&&<Modal title="Your guide to the EP lab" onClose={()=>setModal(null)} wide><LearningGuide onStart={startTour} onModule0={openModule}/></Modal>}
  {modal==='protocol'&&<Modal title="Working with programmed stimulation" onClose={()=>setModal(null)}><div className="learning-guide"><p>S1 is a train of evenly spaced paced beats. S2 is one extra beat after the final S1. A shorter coupling interval probes tissue before it has fully recovered.</p><p>Output and pulse width determine whether the nearby tissue captures. Check the procedure log: an artifact without capture is not a successful intervention.</p><h3>For this case</h3><p>{lesson.tasks.join(' ')}</p><p className="quiet">{lesson.limit}</p><button className="button subtle" onClick={()=>setModal('help')}>Open the EP glossary</button></div></Modal>}

 </div>;
}
